### ISSUE TITLE
the PodPreset feature is deprecated, any other way the set timezone?

### ISSUE THREAD

**Issue by huxin889** [arangodb/kube-arangodb#1023]
the PodPreset feature is deprecated, any other way the set timezone for all pods?

**Comment by huxin889** [comment]
![image](https://user-images.githubusercontent.com/4258636/174608703-0d386a65-5487-4276-847e-27b582735e6b.png)
even thought, I declared the volume type to _HostPath_, howere the volume is _EmptyDir_ in the pod outputting information
![image](https://user-images.githubusercontent.com/4258636/174608953-73df4ba4-b8f4-4b04-a0d2-cd6b57cfb4d7.png)

**Comment by huxin889** [comment]
> Hello!
> 
> Did you try to add TZ env or mount the proper file under `/etc/localtime` in the container?
> 
> Example for env (you need to set it to each group):
> 
> ```
> spec:
>   dbservers:
>     envs:
>       - name: TZ
>          value: Europe/Warsaw
> ```
> 
> Best Regards, Adam.

thanks for your replying, I have tried for this method, but it didn't work for me, I thought it was caused by that there was no any file in /usr/share/zoneinfo/...

**Comment by ajanikow** [comment]
Which Operator version do you use? HostPath support has been added in 1.2.13

**Comment by ajanikow** [comment]
Can you try with 1.2.13?

Ref: https://github.com/arangodb/kube-arangodb/blob/master/CHANGELOG.md?plain=1#L35

**Comment by huxin889** [comment]
> Can you try with 1.2.13?
> 
> Ref: https://github.com/arangodb/kube-arangodb/blob/master/CHANGELOG.md?plain=1#L35

of course, I will try to upgrade the operator as soon as possible, thx for your guidance.

**Comment by huxin889** [comment]
> Can you try with 1.2.13?
> 
> Ref: https://github.com/arangodb/kube-arangodb/blob/master/CHANGELOG.md?plain=1#L35

@ajanikow After upgrading kube-arangodb to 1.2.13, it works for me. thank you very much.

**Comment by ajanikow** [comment]
I will leave issue for documentation purposes - once Docs gonna be ready I will close issue,

Thank You!
