### ISSUE TITLE
how to connect to the single server database with pyarango

### ISSUE THREAD

**Issue by liulfy** [arangodb/kube-arangodb#1064]
when I deployment a single server database using the following yaml:
apiVersion: "database.arangodb.com/v1alpha"
kind: "ArangoDeployment"
metadata:
  name: "single-server"
spec:
  mode: Single
I don't know where to set the user and password and I cannot connect to this database with pyarango.

**Comment by ajanikow** [comment]
Hello!

If you set this https://www.arangodb.com/docs/stable/deployment-kubernetes-deployment-resource.html#specbootstrappasswordsecretnamesroot-string to auto then secret with credentials will be generated.

By default your username is `root` and password is empty.

Best Regards,
Adam.

**Comment by liulfy** [comment]
thanks!
