### ISSUE TITLE
How to run arangodb deployed in k8s

### ISSUE THREAD

**Issue by liulfy** [arangodb/kube-arangodb#1098]
I installed arangodb using kubectl like this:

kubectl apply -f https://raw.githubusercontent.com/arangodb/kube-arangodb/1.2.15/manifests/arango-crd.yaml
kubectl apply -f https://raw.githubusercontent.com/arangodb/kube-arangodb/1.2.15/manifests/arango-deployment.yaml
kubectl apply -f https://raw.githubusercontent.com/arangodb/kube-arangodb/1.2.15/manifests/arango-storage.yaml
kubectl apply -f https://raw.githubusercontent.com/arangodb/kube-arangodb/1.2.15/manifests/arango-deployment-replication.yaml

and the state is as following:
kubectl -narango2 get pod
NAME                                                      READY   STATUS    RESTARTS   AGE
arango-deployment-operator-f445574df-lzd24                1/1     Running   0          37m
arango-deployment-operator-f445574df-zchqp                1/1     Running   0          37m
arango-deployment-replication-operator-7776796c87-cfwgh   1/1     Running   0          34m
arango-deployment-replication-operator-7776796c87-f7vnq   1/1     Running   0          34m
arango-storage-operator-5cd4687dff-287mk                  1/1     Running   0          36m
arango-storage-operator-5cd4687dff-rwdv2                  1/1     Running   0          36m

kubectl -narango2 get deployment
NAME                                     READY   UP-TO-DATE   AVAILABLE   AGE
arango-deployment-operator               2/2     2            2           37m
arango-deployment-replication-operator   2/2     2            2           34m
arango-storage-operator                  2/2     2            2           36m

kubectl -narango2 get service
NAME                                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
arango-deployment-operator               ClusterIP   xx.xx.xx.xx   <none>        8528/TCP   38m
arango-deployment-replication-operator   ClusterIP   xx.xx.xx.xx   <none>        8528/TCP   34m
arango-storage-operator                  ClusterIP   xx.xx.xx.xx   <none>        8528/TCP   36m

It seems the arangodb is installed successfully, but there are no external ip of the services, and I don't know how to get access to the arangodb.  Could you please give me a hand? I prefer to use pyarango. Thanks~

**Comment by ajanikow** [comment]
Hello!

You only have installed Operator, now you can install ArangoDeployment. See the examples directory for more details.

Best Regards,
Adam.

**Comment by liulfy** [comment]
Thanks, I solve this problem. Besides, I didn't find the cpu and memory config, could you please info me about this?
