### ISSUE TITLE
Exporter using invalid JWT to access metrics endpoint

### ISSUE THREAD

**Issue by radicaled** [arangodb/kube-arangodb#1109]
I recently upgraded kube-arangodb to 1.2.16 (from 1.1.9). After routine node maintenance a week later, the `/metrics` endpoint now returned this message:

```
{"error":true,"errorNum":11,"errorMessage":"not authorized to execute this request","code":401}
```

After some digging, I noticed that the JWT used by the exporter at `/secrets/exporter/jwt/token` has this payload:

```
{
  "allowed_paths": [
    "/_admin/statistics",
    "/_admin/statistics-description",
    "/_admin/metrics"
  ],
  "iss": "arangodb",
  "server_id": "exporter"
}
```

And that the command line arguments for the exporter now look like this:

```
/lifecycle/tools/arangodb_operator
    exporter
    --arangodb.endpoint=https://localhost:8529/_admin/metrics/v2
    --arangodb.jwt-file=/secrets/exporter/jwt/token
```

My guess here is that the JWT token being used from my 1.1.9 installation isn't authorized to access the new metrics endpoint being used. The JWT has no expiry date, so I guess it won't be automatically regenerated anytime soon.

How should I deal with this so that a new JWT for the exporter is generated, with the correct paths?

**Comment by ajanikow** [comment]
Hello @radicaled!

Can you remove the secret? The operator will recreate it with proper values.

Best Regards,
Adam.

**Comment by radicaled** [comment]
I deleted the secret with `kubectl delete secret/arangodb-cluster-exporter-jwt-token` and now the metrics exporter is in good condition again, thanks!

> Do you have any errors in operator log output?

The only things that stick out from the last 2 weeks of logs are these lines from kube-arangodb, written to STDOUT:

```
DBG Cluster inspection failed error="JWT Secret is invalid" name= namespace=default operator-id=hsklt
ERR Unable to get secret error="secrets \"arangodb-cluster-jwt-folder\" not found" name=arangodb-cluster namespace=default operator-id=hsklt
```

These lines are fairly recent (September 12th), but the problem occurred somewhere between August 31st and September 1st. Otherwise, the logs look fine and dandy.

**Comment by ajanikow** [comment]
@radicaled Hello!

It is normal for upgrade procedure - Operator works on few threads, so secret was not yet created. It was a huge jump in regards to versions, we will fix the monitoring secret validator (to make sure it will recreate the secret if needed).

Can we close this issue?

Best Regards,
Adam.

**Comment by radicaled** [comment]
Sure, no problem, thanks for the assistance!
