### ISSUE TITLE
Helm charts were not uploaded for 1.2.16

### ISSUE THREAD

**Issue by ddelange** [arangodb/kube-arangodb#1110]
Hi 👋 

For the latest release, [there are no](https://github.com/arangodb/kube-arangodb/releases) release assets (helm charts).

Could you check what went wrong?

**Comment by ajanikow** [comment]
Hello!

The tool has been changed and did not upload properly. We are working on a fix for the CD.

Best Regards,
Adam.

**Comment by ddelange** [comment]
Super, thanks for checking in!

**Comment by ddelange** [comment]
fwiw here's a small github action that will package and upload all helm charts in a folder whenever a github (draft) release is (pre)released:

https://github.com/ddelange/kserve/blob/deeda68a35636c87fd68fb6f87d642a4e28abfa3/.github/workflows/helm-publish.yml

**Comment by ddelange** [comment]
closing as it looks like fixed
