### ISSUE TITLE
Helm repo isn't getting the latest version of the operator

### ISSUE THREAD

**Issue by wyattwalter** [arangodb/kube-arangodb#1153]
Hi,

In #562 a Helm repo was added and documentation updated. However, the publish process seems to not be happening when a new version of the operator is released. Currently the latest operator version is 1.2.19 and the latest on the Helm repo is 1.2.17. Not sure what is triggering this publication, but can this be investigated?

**Comment by ajanikow** [comment]
Hello!

We found issue in the gh merge part. Due to helm update output was different.

We have fixed this part, all versions up to 1.2.20 are in repository.

Best Regards,
Adam.
