### ISSUE TITLE
Incompatibility with Istio Proxy Sidecars

### ISSUE THREAD

**Issue by jeff-hegerhorst-deepsee** [arangodb/kube-arangodb#1201]
## Issue
I'm having issues with the 1.2.20 operator when running pods with istio sidecars. There's an issue with the sidecar not being able to spin up when using this version. I was previously running the operator version 1.2.15 with no issues. It looks like the newer operator is creating services after it scans a pod for all exposed ports in all containers of a pod and creating a service targeting those ports. It looks like that's what's causing the issue as I'm getting logs in the istio sidecar indicating an issue with an existing listener being on a port that the sidecar is exposing

## How to Recreate
I ran the following in a local kind cluster with the following version info
```
❯ kind --version && kubectl version --short
kind version 0.17.0
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.25.3
```

The following commands will recreate the issue that I'm seeing
```
# Install Istio
helm repo add istio https://istio-release.storage.googleapis.com/charts
helm repo update

kubectl create ns istio-system
helm install -n istio-system istio-base istio/base
helm install -n istio-system istiod istio/istiod

# Create a namespace to deploy Arango
export ARANGO_NAMESPACE=default
kubectl label namespace $ARANGO_NAMESPACE istio-injection=enabled

# Install the operator
export URLPREFIX=https://raw.githubusercontent.com/arangodb/kube-arangodb/1.2.20/manifests
kubectl apply -f $URLPREFIX/arango-crd.yaml
kubectl apply -n $ARANGO_NAMESPACE -f $URLPREFIX/arango-deployment.yaml

cat <<EOF | kubectl apply -n $ARANGO_NAMESPACE -f -
apiVersion: "database.arangodb.com/v1alpha"
kind: "ArangoDeployment"
metadata:
  name: arangodb-istio
spec:
  mode: Single
  image: arangodb/arangodb:3.10.1
EOF
```

## Additional Details
After the above has been deployed to the cluster you'll see this:
```
NAME                                          READY   STATUS    RESTARTS   AGE
arango-deployment-operator-654c479968-lkhxb   2/2     Running   0          90s
arango-deployment-operator-654c479968-skn4p   2/2     Running   0          90s
arangodb-istio-sngl-eptwx2i0-a4c686           1/2     Running   0          31s
```
The arangodb-istio-sngl pod's arangodb container spins up fine, but the istio-proxy container won't ever be ready. If you look at the istio proxy logs e.g.
```
kubectl logs -c istio-proxy arangodb-istio-sngl-eptwx2i0-a4c686
```
You'll see these logs:
```
2022-12-07T20:48:15.293196Z warning envoy config  error adding listener: '0.0.0.0_15090' has duplicate address '0.0.0.0:15090' as existing listener
2022-12-07T20:48:15.307569Z warning envoy config  gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 0.0.0.0_15090: error adding listener: '0.0.0.0_15090' has duplicate address '0.0.0.0:15090' as existing listener
```
Port 15090 is the http-envoy-prom port exposed in the istio sidecar and you can see in the service definition(s) that the operator created is targeting that port as well
```
❯ kubectl get svc
NAME                             TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
arango-deployment-operator       ClusterIP   10.96.79.57     <none>        8528/TCP,8628/TCP,8728/TCP   20m
arangodb-istio                   ClusterIP   10.96.165.216   <none>        8529/TCP                     19m
arangodb-istio-ea                NodePort    10.96.18.11     <none>        8529:31443/TCP               18m
arangodb-istio-int               ClusterIP   None            <none>        8529/TCP                     19m
arangodb-istio-single-eptwx2i0   ClusterIP   10.96.91.191    <none>        8529/TCP,15090/TCP           19m
```
Attached is the yaml for the pod
[pod.txt](https://github.com/arangodb/kube-arangodb/files/10186505/pod.txt)

**Comment by ajanikow** [comment]
Hello!

We will add the possibility to ignore some ports (especially the Istio one).

Can you share Pod YAML?

Best Regards,
Adam.

**Comment by jeff-hegerhorst-deepsee** [comment]
Sure, I updated the original comment to include an attachment of the yaml for the pod. Thanks!

**Comment by ajanikow** [comment]
Hello @jeff-hegerhorst-deepsee !

Above fix will change logic - it wont use anymore current Pod, just saved definition (so before Istio Webhook).

**Comment by jeff-hegerhorst-deepsee** [comment]
Awesome. Thanks!
