### ISSUE TITLE
Add ability to use an existing Persistent Volume Claim

### ISSUE THREAD

**Issue by vanthome** [arangodb/kube-arangodb#1271]
It is good practice to allow to use pre-created PVCs like here in this Kafka helm chart:

https://artifacthub.io/packages/helm/bitnami/kafka#persistence-parameters

using the `persistence.existingClaim` property. Would be nice if you can add support for this as well.

**Comment by ajanikow** [comment]
Hello!

It is possible, but in EE Version with Operator.

In this version, the Operator will be able to create member IDs like stateful set (0000, 0001 ...). This allows you to pre-create PVCs if needed.

In CE you can create deployment with pre-filled member IDs in status to have same (check your current deployment status field and propagate same values (just memberIDs).

Best,
Adam.

**Comment by jwierzbo** [comment]
We have a doc for that:
https://github.com/arangodb/kube-arangodb/blob/master/docs/design/recovery.md#create-arangodeployment-with-previously-created-pvc

**Comment by vanthome** [comment]
@jwierzbo thanks, much appreciated. Does this also work for single agent installation? 
I also cannot find those properties you are using in the docs: https://www.arangodb.com/docs/devel/deployment-kubernetes-helm.html

**Comment by jwierzbo** [comment]
@vanthome yes it works for Single mode as well. Just use: `single.volumeClaimTemplate`
