### ISSUE TITLE
High vulnerability in gopkg.in/yaml.v3 module - Update to version 3.0.0 needed

### ISSUE THREAD

**Issue by jbrizio** [arangodb/kube-arangodb#1273]
Hi there,

I hope this message finds you well. I wanted to reach out to you regarding a potential security issue that has been reported in the `gopkg.in/yaml.v3` module.

Recently, a high vulnerability was reported in this module, and I wanted to bring it to your attention in case you haven't already seen it. The details of the vulnerability can be found here: https://github.com/advisories/GHSA-hp87-p4gw-j4gq.

To address this issue, I strongly recommend updating the `gopkg.in/yaml.v3` module to version 3.0.0.
I was wondering if you have any information on when release 1.2.25 with the fix is scheduled.

Thank you for your attention to this matter, and happy coding! 💪🏻😎

**Comment by jbrizio** [comment]
@ajanikow This issue will be resolved in release 1.2.25, right?. Do you have a tentative date?. Thanks.

**Comment by ajanikow** [comment]
Hello!

The above dependency is only a Test dependency (used by the internal package to render YAML files during generate procedure).

```
ubuntu@ubuntu:~/GIT/arangodb/kube-arangodb-release-manager/modules/community$ go mod why gopkg.in/yaml.v3
# gopkg.in/yaml.v3
github.com/arangodb/kube-arangodb/internal
gopkg.in/yaml.v3
```

We do not use it in Released binaries.

It will be fixed with the next release.

Best Regards,
Adam.

**Comment by ajanikow** [comment]
1.2.25 Released
