### ISSUE TITLE
OpenShift: No DB is getting deployed

### ISSUE THREAD

**Issue by gkarthiks** [arangodb/kube-arangodb#128]
So I followed the guide for deploying ArangoDB in the OpenShift Cluster. The `CRD` and the `arango-deployment-operator` has been created. When I ran the `single-server` deployment command, nothing happened in the cluster. But the `CLI` on the terminal shows its created.

Upon running the `kubectl describe ArangoDeployment single-server` command, it gives me the below output.

```
Name:         single-server
Namespace:    data-fabric
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"database.arangodb.com/v1alpha","kind":"ArangoDeployment","metadata":{"annotations":{},"name":"single-server","namespace":"data-fabric"},...
API Version:  database.arangodb.com/v1alpha
Kind:         ArangoDeployment
Metadata:
  Cluster Name:                   
  Creation Timestamp:             2018-04-27T05:33:06Z
  Deletion Grace Period Seconds:  <nil>
  Deletion Timestamp:             <nil>
  Resource Version:               73456034
  Self Link:                      /apis/database.arangodb.com/v1alpha/namespaces/data-fabric/arangodeployments/single-server
  UID:                            76a59a8a-49dc-11e8-b98d-fa163e3d2f07
Spec:
  Mode:  Single
Events:  <none>
```

followed by running the below command  
```
kubectl get pods --selector=arango_deployment=single-server
```

gives `No Resources found`. Because nothing is created.  Also interestingly the logs from the `arango-deployment-operator` prints the following as attached in the below log file.
[arango-deployment-operator-1812060196-27kbj.log](https://github.com/arangodb/kube-arangodb/files/1953956/arango-deployment-operator-1812060196-27kbj.log)

version:
OpenShift: 3.7
Kubernetes: 1.7

**Comment by ewoutp** [comment]
From the logs, it looks that either the kubernetes cluster is not happy (log shows several connection errors to the apiserver).
The other possibility is that this kubernetes cluster is too old.
We've not tested on 1.7 and we assume a minimum of 1.8

**Comment by ewoutp** [comment]
We've tried running kube-arangodb on minishift.
It does not work yet. There is a problem with a user permission (when using all default settings) and minishift is indeed based on an "old" kubernetes version.

We'll investigate further and keep this issue open.

**Comment by gkarthiks** [comment]
Any updates on this?

**Comment by gkarthiks** [comment]
nice, let me try with the latest image @ewoutp

**Comment by ewoutp** [comment]
Progress is being made, see #144

**Comment by ewoutp** [comment]
With arangodb 3.3.10 & the latest operator (in master branch) this should be solved.

**Comment by gkarthiks** [comment]
Thanks, @ewoutp The DB is getting deployed successfully. But couldn't run the foxx UI.

I am trying to deploy the `single-server` and I am having two services. `single-server-init` and `single-server`. So I am creating a route for the `single-server`. But when I hit that URL. it says

`502 Bad Gateway`. Am i missing anything here?

**Comment by gkarthiks** [comment]
Sorry, it worked with the route and port together. Thanks @ewoutp !
