### ISSUE TITLE
How to delete arangodeployments ?

### ISSUE THREAD

**Issue by raphael10-collab** [arangodb/kube-arangodb#1284]
I'm having difficulty in deleting existing arangodeployments : 
    
    root@k8s-eu-1-master:~# kubectl get arangodeployments -o wide
    NAME                      AGE
    arangocluster             21d
    cluster                   174m
    cluster-using-local-ssh   8h

    root@k8s-eu-1-master:~# kubectl delete arangodeployments arangocluster --force
    Warning: Immediate deletion does not wait for confirmation that the running resource has been terminated. The resource may continue to run on the cluster indefinitely.
    arangodeployment.database.arangodb.com "arangocluster" force deleted

    root@k8s-eu-1-master:~# kubectl get arangodeployments -o wide
    NAME                      AGE
    arangocluster             21d
    cluster                   176m
    cluster-using-local-ssh   8h

And I didn't succeed in applying what is suggested here: https://github.com/arangodb/kube-arangodb/issues/224#issuecomment-407744532  : 

    root@k8s-eu-1-master:~# kubectl -n default get pod | grep 'agnt\|prmr' | awk '{print $1}' | xargs -ri kubectl -n default patch pod {} -p '{"metadata":{"finalizers":[]}}' --type=merge
    No resources found in default namespace.
    root@k8s-eu-1-master:~# kubectl get pod | grep 'agnt\|prmr' | awk '{print $1}' | xargs -ri kubectl patch pod {} -p '{"metadata":{"finalizers":[]}}' --type=merge
    No resources found in default namespace.

And I also didn't succeed using the `arangoDeployment.yaml` file : 

    root@k8s-eu-1-master:~# kubectl delete -f arangoDeployment.yaml 
    arangodeployment.database.arangodb.com "cluster" deleted
    ^Croot@k8s-eu-1-master:~# 
    root@k8s-eu-1-master:~# kubectl get arangodeployments
    NAME                      AGE
    arangocluster             21d
    cluster                   3h51m
    cluster-using-local-ssh   9h

**Comment by jwierzbo** [comment]
@raphael10-collab you need to have operator running to handle the arangodeployment delete request.

If there is no more operator you can try to remove finalizer from particular arangodeployment and then remove it

**Comment by raphael10-collab** [comment]
Hi @jwierzbo | How to remove the finalizer from the particular arangodeployment, then?

**Comment by raphael10-collab** [comment]
@jwierzbo I found how to remove the finalizer from the particular arangodeployment:  

    root@k8s-eu-1-master:~# kubectl patch ArangoDeployment/cluster --type json --patch='[ { "op": "remove", "path": "/metadata/finalizers" } ]'
    arangodeployment.database.arangodb.com/cluster patched
    root@k8s-eu-1-master:~# 
    root@k8s-eu-1-master:~# 
    root@k8s-eu-1-master:~# kubectl get arangodeployments
    NAME                      AGE
    arangocluster             21d
    cluster-using-local-ssh   9h
    root@k8s-eu-1-master:~# 
    root@k8s-eu-1-master:~# kubectl patch ArangoDeployment/arangocluster --type json --patch='[ { "op": "remove", "path": "/metadata/finalizers" } ]'
    arangodeployment.database.arangodb.com/arangocluster patched
    root@k8s-eu-1-master:~# kubectl get arangodeployments
    NAME                      AGE
    cluster-using-local-ssh   9h
    root@k8s-eu-1-master:~# kubectl patch ArangoDeployment/cluster-using-local-ssh --type json --patch='[ { "op": "remove", "path": "/metadata/finalizers" } ]'
    arangodeployment.database.arangodb.com/cluster-using-local-ssh patched
    root@k8s-eu-1-master:~# kubectl get arangodeployments
    No resources found in default namespace.

Thank you @jwierzbo !!
