### ISSUE TITLE
I've tried to access the database using https://ip-node:8529 of the 6 nodes of the cluster but I got "This site can’t be reached. xx.xxx.xxx.xxx refused to connect" 

### ISSUE THREAD

**Issue by raphael10-collab** [arangodb/kube-arangodb#1285]
Based on what I read here: https://www.arangodb.com/docs/3.10/deployment-kubernetes-driver-configuration.html I should be able to access my database from the outside, when pointing to the  the IP address(es) of the Nodes of the Kubernetes cluster,followed by the NodePort indicated : 
    
    root@k8s-eu-1-master:~# kubectl get services
    NAME                            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
    arango-kube-arangodb-operator   ClusterIP   10.99.176.37     <none>        8528/TCP,8628/TCP,8728/TCP   78m
    cluster                         ClusterIP   10.100.129.11    <none>        8529/TCP                     71m
    cluster-agent-apt6zd1n          ClusterIP   10.100.221.87    <none>        8529/TCP                     70m
    cluster-agent-mwchqsli          ClusterIP   10.109.165.148   <none>        8529/TCP                     70m
    cluster-agent-uhbsq34m          ClusterIP   10.101.160.58    <none>        8529/TCP                     70m
    cluster-coordinator-2avzgbi1    ClusterIP   10.107.1.167     <none>        8529/TCP                     70m
    cluster-coordinator-ets3nigq    ClusterIP   10.107.55.242    <none>        8529/TCP                     70m
    cluster-coordinator-n3r0x9by    ClusterIP   10.99.135.125    <none>        8529/TCP                     70m
    cluster-dbserver-07wqascu       ClusterIP   10.104.138.185   <none>        8529/TCP                     70m
    cluster-dbserver-kenmxcns       ClusterIP   10.96.32.137     <none>        8529/TCP                     70m
    cluster-dbserver-nsgmx9lg       ClusterIP   10.101.167.36    <none>        8529/TCP                     70m
    cluster-ea                      NodePort    10.96.65.142     <none>        8529:32527/TCP               70m
    cluster-int                     ClusterIP   None             <none>        8529/TCP                     71m
    kubernetes                      ClusterIP   10.96.0.1        <none>        443/TCP                      25d
    local-storage                   ClusterIP   10.97.243.65     <none>        8929/TCP                     72m

    
    root@k8s-eu-1-master:~# kubectl get service -n default cluster-ea
    NAME         TYPE       CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
    cluster-ea   NodePort   10.96.65.142   <none>        8529:32527/TCP   74m

My cluster is made up of one master node and 5 worker nodes:

    root@k8s-eu-1-master:~# kubectl get nodes
    NAME                STATUS   ROLES           AGE   VERSION
    k8s-eu-1-master     Ready    control-plane   25d   v1.26.2
    k8s-eu-1-worker-1   Ready    <none>          25d   v1.26.2
    k8s-eu-1-worker-2   Ready    <none>          25d   v1.26.2
    k8s-eu-1-worker-3   Ready    <none>          25d   v1.26.2
    k8s-eu-1-worker-4   Ready    <none>          25d   v1.26.2
    k8s-eu-1-worker-5   Ready    <none>          22d   v1.26.2
    root@k8s-eu-1-master:~# 

I've tried to access the database using https://ip-node:8529 of the 6 nodesof the cluster but I got "This site can’t be reached. xx.xxx.xxx.xxx refused to connect"

What am I doing wrong or am I missing?

**Comment by jwierzbo** [comment]
1. For connection please use `cluster-ea` service
2. What is you TLS config in ArangoDeployment? If you disabled it, then please use http

**Comment by raphael10-collab** [comment]
Hi @jwierzbo ! 

TLS config is not specified in `ArangoDeployment` : 

`arangoDeployment.yaml` : 

    apiVersion: "database.arangodb.com/v1"
    kind: "ArangoDeployment"
    metadata:
      name: "cluster"
    spec:
      mode: Cluster
      agents:
        volumeClaimTemplate:
          spec:
            storageClassName: my-local-ssd
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
            volumeMode: Filesystem
      dbservers:
        volumeClaimTemplate:
          spec:
            storageClassName: my-local-ssd
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
            volumeMode: Filesystem

With http://node-ip:8529 I cannot connect either

**Comment by ajanikow** [comment]
Hello!

As NodePort expose port on HighPorts defined in K8S (as it is described in output):
```
root@k8s-eu-1-master:~# kubectl get service -n default cluster-ea
NAME         TYPE       CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
cluster-ea   NodePort   10.96.65.142   <none>        8529:32527/TCP   74m
```

Try to connect to `http://node-ip:32527/` or, if you will get Empty Response, `https://node-ip:32527/`.

Best,
Adam.

**Comment by raphael10-collab** [comment]
Hi @ajanikow !

With http://node-ip:32527/ I get :  


![Uploading image.png…]()

**Comment by raphael10-collab** [comment]
With https://node-ipc:32527/_db/_system/_admin/aardvark/index.html#login 

![image](https://user-images.githubusercontent.com/70313067/231115534-dc7a5459-780c-4745-9a81-85e555905828.png)


Thank you !!

**Comment by raphael10-collab** [comment]
Sorry @ajanikow .... I feel ashamed about this.... what are the username and password that I have to use?
