### ISSUE TITLE
How to synchronize the endpoints?

### ISSUE THREAD

**Issue by raphael10-collab** [arangodb/kube-arangodb#1286]
Linked question to the one I raised yesterday: https://github.com/arangodb/kube-arangodb/issues/1285#issue-1658646903

Here: https://www.arangodb.com/docs/3.10/deployment-kubernetes-driver-configuration.html#query-requests I read: 

"**To prevent this uncertainty client-side, make sure to run your client application in the same Kubernetes cluster and synchronize your endpoints before making the initial query request. 
This will result in the use (by the driver) of internal DNS names of all Coordinators. A follow-up request can then be sent to exactly the same Coordinator**"

How to synchronize the endpoints?
    
    root@k8s-eu-1-master:~# kubectl get endpoints
    NAME                                     ENDPOINTS                                                                  AGE
    arango-deployment-operator               <none>                                                                     24d
    arango-deployment-replication-operator   <none>                                                                     24d
    arango-kube-arangodb-operator            192.168.104.54:8628,192.168.104.54:8528,192.168.104.54:8728                28h
    arango-storage-operator                  <none>                                                                     2d
    cluster                                  192.168.104.56:8529,192.168.200.63:8529,192.168.236.53:8529                28h
    cluster-agent-apt6zd1n                   192.168.198.132:8529                                                       28h
    cluster-agent-mwchqsli                   192.168.104.57:8529                                                        28h
    cluster-agent-uhbsq34m                   192.168.165.69:8529                                                        28h
    cluster-coordinator-2avzgbi1             192.168.200.63:8529                                                        28h
    cluster-coordinator-ets3nigq             192.168.104.56:8529                                                        28h
    cluster-coordinator-n3r0x9by             192.168.236.53:8529                                                        28h
    cluster-dbserver-07wqascu                192.168.104.58:8529                                                        28h
    cluster-dbserver-kenmxcns                192.168.200.1:8529                                                         28h
    cluster-dbserver-nsgmx9lg                192.168.200.2:8529                                                         28h
    cluster-ea                               192.168.104.56:8529,192.168.200.63:8529,192.168.236.53:8529                28h
    cluster-int                              192.168.104.56:8529,192.168.104.57:8529,192.168.104.58:8529 + 6 more...    28h
    kubernetes                               38.242.250.38:6443                                                         26d
    local-storage                            192.168.104.55:8929,192.168.165.68:8929,192.168.198.131:8929 + 2 more...   28h

**Comment by ajanikow** [comment]
Hello!

It is done by the driver, everything depends on which one you use.

For example, you have https://github.com/arangodb/go-driver/blob/master/client.go#L41 in Go implementation.

Best,
Adam.

**Comment by raphael10-collab** [comment]
Hi @ajanikow !

I didn't find an equivalent function of  "SynchronizeEndpoints" for arangojs, the JS implementation of the driver, to fetch all the endpoints from the Arangodb Cluster and update the connections to use these endpoints

https://github.com/arangodb/arangojs

**Comment by jwierzbo** [comment]
@raphael10-collab please ask for similar function at https://github.com/arangodb/arangojs
