### ISSUE TITLE
1.2.25 installation fails

### ISSUE THREAD

**Issue by jgoodall** [arangodb/kube-arangodb#1288]
When I try to install kube-arangodb 1.2.25 release via helm chart (after successfully installing the kube-arangodb-crd), I get the following error:

```Error: INSTALLATION FAILED: template: kube-arangodb/templates/deployment.yaml:108:34: executing "kube-arangodb/templates/deployment.yaml" at <eq .Values.operator.replicaCount 1.0>: error calling eq: incompatible types for comparison```

I am assuming the 1.0 should be a 1, but not overly familiar with the syntax.

**Comment by jwierzbo** [comment]
@jgoodall what is your OS? Could you share your  full `helm` install command?

**Comment by jgoodall** [comment]
I am on MacOS 13.3.1 (intel chip) using k3d (v5.4.9). We mirror the helm charts and images to an internal harbor server (which is `<host>/<project>` below), and here is the relevant portion of the script we use to initialize the kubernetes cluster:

```
KUBE_ARANGODB_VERSION=1.2.25
op_replica_count=1

helm install arango-crd cav/kube-arangodb-crd \
  --version $KUBE_ARANGODB_VERSION

helm install arango-deployment \
  --version $KUBE_ARANGODB_VERSION \
  --set "operator.image=<host>/<project>/kube-arangodb:${KUBE_ARANGODB_VERSION}" \
  --set "operator.replicaCount=${op_replica_count}" \
  --set "operator.features.deploymentReplications=false" \
  --set "operator.features.storage=true" \
  --set "operator.architectures={amd64,arm64}" \
  --set "operator.metrics=true" \
  cav/kube-arangodb
```

**Comment by jwierzbo** [comment]
if you want to use just one replica (single mode) then skip this line:
` --set "operator.replicaCount=${op_replica_count}" `

Since 1.2.25 Single mode is default

**Comment by jgoodall** [comment]
Removing it worked. And if I just set it `operator.replicaCount=1`, seems to be fine, so not sure what the issue was but appears to be my script, not the helm chart. Thanks!
