### ISSUE TITLE
wrong image getting injected

### ISSUE THREAD

**Issue by ac427** [arangodb/kube-arangodb#1294]
We run istio 1-16-2 and see similar [issue](https://github.com/arangodb/kube-arangodb/issues/260) 
Some how it is getting image of istio proxy instead of `arangodb`

We run single server deployment and version `1.2.24`

**Comment by ac427** [comment]
okay. `holdApplicationUntilProxyStarts: true` in [istio](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/) is causing the issue. 
arango deployment doesn't honor the annoitation  `holdApplicationUntilProxyStarts: false` when the server pod is created.

**Comment by sfc-gh-pzawila** [comment]
Hit the same issue with our deployments.

**Comment by jwierzbo** [comment]
It has been fixed within this PR: https://github.com/arangodb/kube-arangodb/commit/cf98e1a3c5222bea4a632ec82f2a2a028558b5fc
