### ISSUE TITLE
Arangodb operator build error when build operator with new commits in github

### ISSUE THREAD

**Issue by mrajadurai2413** [arangodb/kube-arangodb#1301]
Hi Arango Team,

I tried to build arangodb operator with this [pr](https://github.com/arangodb/kube-arangodb/pull/551) steps mentioned in kube-arango GitHub [LINK](https://github.com/arangodb/kube-arangodb#building)

But, I received error [Attached screenshot below]
Please help us to resolve this

![image](https://user-images.githubusercontent.com/111195940/234571711-2aa1525d-dd88-448b-b814-88474194477c.png)

**Comment by nikita-vanyasin** [comment]
Hello @mrajadurai2413
I'm afraid supporting rejected PR is not on our current priority list.

I would recommend rebasing the branch on latest master and then:
`make clean tidy init all`


cc @ajanikow

**Comment by mrajadurai2413** [comment]
@nikita-vanyasin 
In the Arangodb community operator, cluster scope is supported..?

**Comment by jwierzbo** [comment]
No, right now it is only namespace scope
