### ISSUE TITLE
Add documentation about custom initContainers

### ISSUE THREAD

**Issue by MalteJoe** [arangodb/kube-arangodb#1306]
#1303 was created due to missing documentation about the possibility to add custom initContainers to an Arango Deployment Ressource Group.

According to https://github.com/arangodb/kube-arangodb/issues/1303#issuecomment-1527809620 it should be possible right now but this is not documented at https://www.arangodb.com/docs/stable/deployment-kubernetes-deployment-resource.html right now.

**Comment by ajanikow** [comment]
Hello! We are working on the automated API Generator. It is in progress.

**Comment by ajanikow** [comment]
Hello!

We are working on Generator improvements (https://github.com/arangodb/kube-arangodb/blob/master/docs/api/ArangoDeployment.V1.md#specagentsinitcontainerscontainers-corecontainer) - same documentation should soon appear on the main ArangoDB Docs page.

Best Regards,
Adam.
