### ISSUE TITLE
Deleted ArangoBackup cleanup

### ISSUE THREAD

**Issue by 4gsim** [arangodb/kube-arangodb#1386]
How should old deleted ArangoBackup resources be handled? Is it ok if they remain in the cluster? Is there a possibility to automatically delete them?

**Comment by jwierzbo** [comment]
Since last release (1.2.32) there is a `Lifetime` field in `ArangoBackup` which lets to keep backup for the defined X time

https://github.com/arangodb/kube-arangodb/blob/d50f2c97a48cf72803d9a425cefca26916c61b6f/docs/design/backup.md#L3-L17
