### ISSUE TITLE
Recommended Helm Chart deployment and upgrade procedures

### ISSUE THREAD

**Issue by sunnyyip** [arangodb/kube-arangodb#1403]
Hello maintainers,

I noticed that the kube-arangodb-crd chart is [now marked as deprecated](https://github.com/arangodb/kube-arangodb/blob/master/chart/kube-arangodb-crd/Chart.yaml#L3) and the kube-arangodb chart has the [enableCRDManagement default to true](https://github.com/arangodb/kube-arangodb/blob/master/chart/kube-arangodb/values.yaml#L27).

Is the recommendation for Helm/K8s deployment now to solely use the kube-arangodb chart? I ask because [the documentation suggested to deploy the CRDs prior to the operator](https://www.arangodb.com/docs/stable/deployment-kubernetes-usage.html).

If so, what is the recommended deployment/upgrade procedures when using Helm for CRDs, ArangoDB Operator, and ArangoDB Deployment respectively? We're looking to use the Helm Charts for production deployment.

Thank you.

**Comment by ajanikow** [comment]
Hello!

As we do not need more charts for CRD, you do not have to install/upgrade this chart (it will be done as part of the main chart).

Documentation from the repository is the one that is right now up to date, we will also update documentation on the ArangoDB Docs page.

Best Regards,
Adam.
