### ISSUE TITLE
Lack of OpenAPI spec causes issues with tools relying on proper CRDs specs

### ISSUE THREAD

**Issue by roeap** [arangodb/kube-arangodb#1448]
The CRDs developed in this repository do not contain any OpenAPI specs. Many external tools rely on these specs to function properly.

It would be great if these could be added to the CRD definitions.

I'd be happy to add some specs to the CRDs if this is a wanted change and some maintainer agrees to review.

**Comment by nikita-vanyasin** [comment]
Hello @roeap!
Next release of operator (1.2.36) will include a new feature that allows enabling the openapi schema for new CRDs. This will work only for CRDs installed by operator itself - not via charts/manifests.
See https://github.com/arangodb/kube-arangodb/blob/master/docs/crds.md#schema-validation

Beware that this feature is not considered production-ready yet - it will be so in a couple more releases.

Best,
Nikita
