### ISSUE TITLE
Can install arangodb operator 1.2.35 on EKS version 1.27?

### ISSUE THREAD

**Issue by wen830722** [arangodb/kube-arangodb#1561]
Platform | Kubernetes Version | ArangoDB Version | State | Remarks | Provider Remarks
-- | -- | -- | -- | -- | --
Google GKE | 1.21-1.26 | >= 3.6.0 | Production | Don't use micro nodes |  
Azure AKS | 1.21-1.26 | >= 3.6.0 | Production |   |  
Amazon EKS | 1.21-1.26 | >= 3.6.0 | Production |   | Amazon EKS

According to this table, it seems arangodb operator supports EKS version 1.21-1.26.
I'm wondering if the arangodb operator can be installed on EKS 1.27 or later version? Has anyone tried that?

**Comment by ajanikow** [comment]
Hello!

Yes, 1.27-1.28 is safe. We will update the table after release.

Best,
Adam.

**Comment by wen830722** [comment]
Hi Adam,

Got it, thanks for the information!
