### ISSUE TITLE
cpu usage on coordinator pods with operator 1.2.36

### ISSUE THREAD

**Issue by wyattwalter** [arangodb/kube-arangodb#1580]
Hi, I'm testing an upgrade to 1.2.36 operator and noticed a huge increase in CPU usage on the coordinator pods in a completely idle 3-node cluster. 

I have a Grafana dashboard showing CPU usage of the `server` container for my ArangoDB pods in this cluster and pasted it below.

During the upgrade from 1.2.35 to 1.2.36, it doesn't change the `initContainers` on all pods in my deployment, so the issue doesn't show up immediately. But then when I manually delete the pod and let the operator re-create the pod, I see an increase like this. The only difference that I can see that would explain the difference is that the image for the `initContainers` changed.

I've tried this 3 times and it seems to reproduce each time. The version of ArangoDB in the deployment doesn't seem to matter either, it does the same with 3.10.12 and 3.11.6.

Upgrade and then deleted a single coordinator to be re-created:

![image](https://github.com/arangodb/kube-arangodb/assets/558322/f1a44120-95f8-46a8-988f-bc751fefb7f3)

Brand new cluster deployment:

![image](https://github.com/arangodb/kube-arangodb/assets/558322/efcb4f7b-468b-47bd-9af7-07cff7cf43d7)

Is this a known issue? Anything that I should look for? Don't see anything suspicious in pod or operator logs on a quick review.

**Comment by jwierzbo** [comment]
@wyattwalter it will be fixed in 1.2.37 release
