### ISSUE TITLE
Cannot access the database(Minikube)

### ISSUE THREAD

**Issue by 312hzeng** [arangodb/kube-arangodb#1587]
**Issue Description**
I have set up a Minikube cluster with one control-plane node with Docker on Ubuntu 20.04.6 LTS. The cluster was deployed successfully and the link poped up when I ran `minikube service cluster-ea`. The webpage showed an error message: "This page isn’t working. 127.0.0.1 didn’t send any data."

**Environment**
Operating System: Ubuntu 20.04.6 LTS
Minikube: v1.31.2

```
 hongkun@xunjiu:~/cs523$ minikube kubectl -- get nodes
 NAME       STATUS   ROLES           AGE   VERSION
 minikube   Ready    control-plane   34m   v1.27.4
 
```
```

hongkun@xunjiu:~/cs523$ minikube kubectl -- get pods --selector=arango_deployment=cluster
NAME                           READY   STATUS    RESTARTS   AGE
cluster-agnt-avnpca5v-7965d8   1/1     Running   0          86s
cluster-agnt-obuhlbfq-7965d8   1/1     Running   0          86s
cluster-agnt-pcbazimi-7965d8   1/1     Running   0          85s
cluster-crdn-bmel3cx0-7965d8   1/1     Running   0          85s
cluster-crdn-pwkaujdc-7965d8   1/1     Running   0          84s
cluster-crdn-z23g8as0-7965d8   1/1     Running   0          84s
cluster-prmr-1lwyodda-7965d8   1/1     Running   0          85s
cluster-prmr-du7x6bzc-7965d8   1/1     Running   0          85s
cluster-prmr-jt8aoqxz-7965d8   1/1     Running   0          85s
```

```

hongkun@xunjiu:~/cs523$ minikube service cluster-ea
|-----------|------------|-------------|---------------------------|
| NAMESPACE |    NAME    | TARGET PORT |            URL            |
|-----------|------------|-------------|---------------------------|
| default   | cluster-ea | server/8529 | http://192.168.49.2:31110 |
|-----------|------------|-------------|---------------------------|
🏃  Starting tunnel for service cluster-ea.
|-----------|------------|-------------|------------------------|
| NAMESPACE |    NAME    | TARGET PORT |          URL           |
|-----------|------------|-------------|------------------------|
| default   | cluster-ea |             | http://127.0.0.1:44303 |
|-----------|------------|-------------|------------------------|
🎉  Opening service default/cluster-ea in default browser...
👉  http://127.0.0.1:44303
❗  Because you are using a Docker driver on linux, the terminal needs to be open to run it.
```

**Expected Behavior**
I expect to be able to access the database through the poped browser link without encountering errors.

**Actual Behavior**
After opening the link, the page displays an error message: "This page isn’t working. 127.0.0.1 didn’t send any data."

What am I doing wrong or am I missing anything?

**Comment by ajanikow** [comment]
Hello!

By default it is exposed over HTTPS, can you try to access it over https instead of http?

Best,
Adam.

**Comment by 312hzeng** [comment]
> Hello!
> 
> By default it is exposed over HTTPS, can you try to access it over https instead of http?
> 
> Best, Adam.

Hello @ajanikow Adam, thank you for your reply! I tried it as well but it also didnt work for me. I ssh into an ubuntu vm and did all the cluster set up there. Is there a way to access the database without the GUI/through CLI? Thank you

**Comment by jwierzbo** [comment]
@312hzeng The following works for me:
```bash
 minikube service cluster --url
😿  service default/cluster has no node port
http://127.0.0.1:55864
```

and then in separate shell (or from web browser):
```bash
curl -kI https://127.0.0.1:55864/_db/_system/_admin/aardvark/index.html
HTTP/2 405
```

**Comment by 312hzeng** [comment]
> @312hzeng The following works for me:
> 
> ```shell
>  minikube service cluster --url
> 😿  service default/cluster has no node port
> http://127.0.0.1:55864
> ```
> 
> and then in separate shell (or from web browser):
> 
> ```shell
> curl -kI https://127.0.0.1:55864/_db/_system/_admin/aardvark/index.html
> HTTP/2 405
> ```

Thank you it worked! I'll close the issue
