### ISSUE TITLE
Provide for global IP addresses on Google Cloud Clusters (GKE)

### ISSUE THREAD

**Issue by theoks** [arangodb/kube-arangodb#159]
The operator creates a load balancer using a regional IP address. If someone tries to set a reserved, static, global IP, it's not possible and the cluster is accessible only within IPs belonging in the same Google Cloud region. There should be an option to enable users to access the cluster from any IP address, global or regional.

**Comment by ex-nerd** [comment]
Do we know if this has even been looked at?  It seems like a pretty big oversight to end up with an ephemeral IP address that might change during a cluster maintenance event, so inability to assign a reserved/static IP seems like a pretty important feature to be missing.

**Comment by informalict** [comment]
Is there a special reason why you want to use global static address IP?

Suggestion:
You can use external static regional static IP which must belong to the same region where your cluster belongs.

**Comment by ex-nerd** [comment]
@informalict How do you do that? I don't see any documentation that allows you to specify any kind of reserved/static IP (external or internal).  I just want to be able to ensure that my cluster has a *known* IP rather than picking up whatever ephemeral addresses get assigned to it.

**Comment by informalict** [comment]
GCP -> VPC network -> External IP address:
Reserve static address:
Type: regional
Region: the same where you have got the cluster

https://github.com/arangodb/kube-arangodb/blob/master/docs/Manual/Deployment/Kubernetes/DeploymentResource.md
You need two settings from the above documentation:
spec.externalAccess.type: LoadBalancer
spec.externalAccess.loadBalancerIP: <YOUR EXTERNAL REGIONAL IP>
