### ISSUE TITLE
How do I configure using custom pvc as data storage?

### ISSUE THREAD

**Issue by xiashengjie** [arangodb/kube-arangodb#1595]
How do I configure using custom pvc as data storage?
Can you give an example?

**Comment by ajanikow** [comment]
Hello!

By custom PVC - do you mean manually created PVC Objects?

Best,
Adam.

**Comment by xiashengjie** [comment]
Yes, I am using juicefs to do storage and calculation separation for arangodb on k8s; therefore, I do not want to use local storage; I manually created a pvc. I would like to know how to configure the arangodb cluster on k8s to use the pvc I created by myself as data storage. @ajanikow

**Comment by ajanikow** [comment]
Hello!

Which mode is interesting for you - Single/Cluster?

And which versions of ArangoDB/Operator do you use? CE or EE?

Best Regards,
Adam.

**Comment by xiashengjie** [comment]
I want to do this on cluster mode and I'm using the CE version，Looking forward to your reply @ajanikow

**Comment by ajanikow** [comment]
Hello!

For cluster mode in CE, it will be tricky.

In EE we can change member indexing, which will enable us to use predictable member names.

For CE you need to prepare your own ArangoDeployment Status, like described here: https://arangodb.github.io/kube-arangodb/docs/how-to/recovery.html#initial-arangodeployment

Best Regards,
Adam.

**Comment by xiashengjie** [comment]
I mean that I have a pvc containing a database file, and I just want to change the database path to access the pvc in cluster mode, like setting the --database.directory parameter. Can this operation be implemented? @ajanikow

**Comment by xiashengjie** [comment]
I want to store the data on another node instead of using local storage. Is it possible to do so according to the sample document you gave? @ajanikow
