### ISSUE TITLE
Set seccompProfile on pod level

### ISSUE THREAD

**Issue by 4gsim** [arangodb/kube-arangodb#1638]
Can you please add the possibility to set the seccompProfile on the pod level for the arango pods?

**Comment by ajanikow** [comment]
Hello!

Like this: https://arangodb.github.io/kube-arangodb/docs/api/ArangoDeployment.V1.html#specagentssecuritycontextseccompprofile ?

Best Regards,
Adam.

**Comment by 4gsim** [comment]
This configuration only sets the seccompProfile on container level, not on pod level.
Please have a look at [https://github.com/arangodb/kube-arangodb/blob/e10ac2662ccbea6a61f1b8fcbbf3d566fae50553/pkg/apis/deployment/v2alpha1/server_group_security_context_spec.go#L110](url)

**Comment by ajanikow** [comment]
Understood! It is there, but not used in the PodRenderer - we will fix this part.

**Comment by ajanikow** [comment]
Fixed in 1.2.40
