### ISSUE TITLE
Specifying additional cert SANs in CRD (i.e. ArangoDeployment)

### ISSUE THREAD

**Issue by chxxvi** [arangodb/kube-arangodb#1670]
Seem it is not possible to specify additional cert SANs through CRD (i.e. `ArangoDeployment`).  It will be great if this feature is available.

**Comment by ajanikow** [comment]
Hello!

Can you try with this option: https://arangodb.github.io/kube-arangodb/docs/api/ArangoDeployment.V1.html#spectlsaltnames  ?

We will change typo in the documentation, it is `These names can be DNS names or **IP** addresses`

Best Regards,
Adam.
