### ISSUE TITLE
arangodb_operator debug-package produces a broken tar archive

### ISSUE THREAD

**Issue by ottojolanki** [arangodb/kube-arangodb#1786]
Hello,
I am running `kube-arangodb` operator version `1.2.43` and ArangoDB version 3.12.3. Kubernetes version is 1.31, which I am running on AWS EKS. I have made the following changes to the default values:
```
operator.features.storage: True
operator.features.backup: True
rbac.extensions.debug: True
```
I am attempting to generate a debug package according to https://arangodb.github.io/kube-arangodb/docs/how-to/debugging.html#deployment-debug-package (As a sidenote, I can successfully create the Agency dump, according to the instruction on the same page, so looks like my permissions to execute commands etc. should be ok.).

As a result, I do get a file that is a little under 400kb in size. Attempt to unpack it results in the following:
```
$ tar -xvzf db.tar.gz 
tar: Error opening archive: Unrecognized archive format
```

The file contains some plain text in the beginning and after that, some binary garbage I cannot decipher:
```
$ head db.tar.gz 
2024-12-18T00:19:45Z INF Fetching factory kubernetes-events
2024-12-18T00:19:45Z INF Fetching factory kubernetes-pods
2024-12-18T00:19:45Z INF Fetching file kubernetes/events.yaml
�2024-12-18T00:19:45Z INF Fetching file kubernetes/pods.yaml
2024-12-18T00:19:45Z INF Fetching file kubernetes/pods/arango-kubernetesstack31clusterchartarangodb4eeb22b5-operad4sjz/pod.yaml
2024-12-18T00:19:45Z INF Fetching file kubernetes/pods/arango-kubernetesstack31clusterchartarangodb4eeb22b5-operad4sjz/logs/container/operator
��is�H�?��c�
���n�tY#����Ƕm������nt�)�Ml�[����H�%J'b��Q��������·k�'#������,������B���ł�����Č����4<B����N3=���W9T����lr=����U1��+ߏF���0����i����� 1&1���)�3���W��M2�����۬�*��x�?Iɨ}
et cetera
```

I do not see any options that would enable me to create the debug dump as an uncompressed format. I would greatly appreciate any help anyone can offer with this issue. 
Thank you!
-Otto

**Comment by ajanikow** [comment]
Hello!

Which Kubectl version do you use?

The issue might be that documentation might be deprecated for never versions of the kubectl (as -ti flag moves STDERR and STDOUT to STDOUT).

Can you try to execute it without -ti flag?

Best Regards,
Adam.

**Comment by ottojolanki** [comment]
Hi Adam, 
first of all, thank you for taking the time to answer. Second, removing `-ti` flag works! So it seems that the problem was the plain text from STDOUT getting mixed in. For the reference for others, the versions you were asking about are:
```
$ kubectl version
Client Version: v1.31.3
Kustomize Version: v5.4.2
Server Version: v1.31.2-eks-7f9249a
```
Thank you!
-Otto
