### ISSUE TITLE
Data loss during acceptance test 5c

### ISSUE THREAD

**Issue by lservini** [arangodb/kube-arangodb#202]
When I killed dbserver a collection with RF3 was gone

[arango-deployment-operator-797544f86d-7w5g2.log](https://github.com/arangodb/kube-arangodb/files/2136432/arango-deployment-operator-797544f86d-7w5g2.log)

**Comment by sleto-it** [comment]
This was related to non ga version 0.2.1 - current version 0.3.9 - closing
