### ISSUE TITLE
Deployment Failed to Start in different Namespace other than Default

### ISSUE THREAD

**Issue by gopigrip7** [arangodb/kube-arangodb#223]
Hi Team, I was trying to use the operator for prod, yes left with no choice. I was trying to setup a arangodb operator in operator Namespace and try to create deployment in the different namespace with below cluster role & binding. 

When I create the deployment in operator namespace, the cluster starts but when trying to do in a different namespace, nothing happens. 

Please point out any bug in my cluster definition.

```apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: arangodb-operator
rules:
- apiGroups: ["extensions"]
  resources: ["deployments", "replicasets", "daemonsets"]
  verbs: ["create", "get", "update", "delete", "list"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["create", "get", "update", "delete", "list"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list", "create", "delete", "deletecollection"]
- apiGroups: [""]
  resources: ["endpoints","persistentvolumes", "persistentvolumeclaims", "services", "secrets", "configmaps","events","namespaces"] 
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["cronjobs", "jobs"]
  verbs: ["create", "get", "deletecollection", "delete"]
- apiGroups: [""]
  resources: ["pods","nodes"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["statefulsets", "deployments","replicasets"]
  verbs: ["*"]
- apiGroups: ["database.arangodb.com"]
  resources: ["arangodeployments"]
  verbs: ["*"]
- apiGroups: ["storage.arangodb.com"]
  resources: ["arangolocalstorages"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: arangodb-operator
  namespace: operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: arangodb-operator
subjects:
- kind: ServiceAccount
  name: arangodb-operator
  namespace: operator```

**Comment by ewoutp** [comment]
hi @gopigrip7 
To run the operator in a different namespace (than `default`), the following must change:

- You must have enough permissions to access the new namespace
- Every reference to namespace default in the YAML files needed to deploy the operators must be changed to the new namespace
- The ArangoDeployment must be deployed in the new namespace.

**Comment by ewoutp** [comment]
Under `tools/manifests` there is a go program you can use to build a YAML file for a specific namespace (look in Makefile for how it is used).
Granted, this is not an easy way and we'll hope to make it easier soon.

**Comment by ewoutp** [comment]
Helm is now available and the preferred solution for deploying in non-default namespaces.
