### ISSUE TITLE
How to Delete ArangoDeployment

### ISSUE THREAD

**Issue by cbluth** [arangodb/kube-arangodb#224]
Please see this:
```
cbluth@dl7490:~/x/arangodb$ kubectl -n platform get ArangoDeployment
NAME       AGE
arangodb   7d
cbluth@dl7490:~/x/arangodb$ kubectl -n platform delete ArangoDeployment arangodb
arangodeployment.database.arangodb.com "arangodb" deleted
cbluth@dl7490:~/x/arangodb$ kubectl -n platform get ArangoDeployment
NAME       AGE
arangodb   7d
cbluth@dl7490:~/x/arangodb$ kubectl -n platform delete ArangoDeployment arangodb --grace-period 0 --force
warning: Immediate deletion does not wait for confirmation that the running resource has been terminated. The resource may continue to run on the cluster indefinitely.
arangodeployment.database.arangodb.com "arangodb" deleted
cbluth@dl7490:~/x/arangodb$ kubectl -n platform get ArangoDeployment
NAME       AGE
arangodb   7d
cbluth@dl7490:~/x/arangodb$
```

How can I remove the `ArangoDeployment`?

**Comment by cbluth** [comment]
I was able to delete these by patching the `metadata.finalizers` value:
```
kubectl -n platform get pod | grep 'agnt\|prmr' | awk '{print $1}' | xargs -ri kubectl -n platform patch pod {} -p '{"metadata":{"finalizers":[]}}' --type=merge
```

Taken from this post here: https://github.com/kubernetes/kubernetes/issues/60538#issuecomment-369099998

**Comment by ewoutp** [comment]
Removing the finalizers will work, but is not "supposed" to be needed.
What the ArangoDB operator still running when you deleted the deployment?
If possible, it would be great that have the logs of the operator and the output of `kubectl get pod`, `kubectl get service`, `kubectl get pvc`, `kubectl get pv`

**Comment by ewoutp** [comment]
We've seen this problem before but so far we've not been able to determine the circumstances under which is happens.
