### ISSUE TITLE
Spot the difference

### ISSUE THREAD

**Issue by cbluth** [arangodb/kube-arangodb#225]
Please note these two image repos:
https://hub.docker.com/r/_/arangodb/
https://hub.docker.com/r/arangodb/arangodb/

What is the difference, and which one should I use?

**Comment by cbluth** [comment]
You can see here that the tags, sizes, and dates are not consistent.

![image](https://user-images.githubusercontent.com/6709636/43264618-ef5ca598-90e6-11e8-9313-7e67e487b45a.png)

![image](https://user-images.githubusercontent.com/6709636/43264624-f31f5504-90e6-11e8-833c-f3e8f033a7d8.png)

**Comment by ewoutp** [comment]
The difference is that the `_/arangodb` one is the (docker) library version, where the `arangodb/arangodb` is the one build by ArangoDB itself. The library version is always 1 or more days behind.

**Comment by cbluth** [comment]
@ewoutp which one is most recommended to use?

**Comment by ewoutp** [comment]
I've forwarded your question to https://github.com/arangodb/arangodb-docker/issues/52.
