### ISSUE TITLE
Tutorials with real world examples

### ISSUE THREAD

**Issue by maku** [arangodb/kube-arangodb#229]
It would be really good to have tutorials for common use cases. 

e.g. running arangodb on GKE in single mode / cluster mode with a simple backend which access the DB (e.g a nodejs backend)

**Comment by janat08** [comment]
I've tried running it following quick guide for gke and permissive advanced settings with all of the options, including full access to cloud apis which I hoped would allow persistent storage. It doesn't appear so:
https://groups.google.com/forum/#!topic/arangodb/FgqVhxcG-bM

**Comment by janat08** [comment]
Anyway perhaps it would be easier to make marketplace offering instead.

**Comment by maku** [comment]
@janat08 Sorry but I don't see a "quickstart guide for gke"...

**Comment by janat08** [comment]
it's a quickstart guide, every google cloud offering has one.

**Comment by maku** [comment]
Yeah of course there are many quick start guides. I would like to have one especially for kubernetes in context with gke and arangodb. When you are not a kubernetes pro this would be really helpful...

**Comment by ewoutp** [comment]
@maku The "Running ArangoDB on GKE" tutorial is indeed on our wishlist. (as well as Amazon, Azure etc)

**Comment by maku** [comment]
@ewoutp Would be cool when "Running ArangoDB on GKE" tutorial is available. (maybe with differentiation between single and cluster mode). 
Is there a time horizon for the tutorials?

**Comment by lamai93** [comment]
[GKE Tutorial](https://github.com/arangodb/kube-arangodb/blob/master/docs/Manual/Tutorials/Kubernetes/GKE.md)
