### ISSUE TITLE
Provide an option to add SubjectAltName or option to disable SSL

### ISSUE THREAD

**Issue by cbluth** [arangodb/kube-arangodb#239]
See here: https://github.com/arangodb/arangojs/issues/566
I have arango 3.3.14 running in kubernetes, and i am trying to use arangojs library.

I am getting this error:
```
{ Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: arangodb.example.com. is not in the cert's altnames: DNS:arango-cluster.platform.svc, DNS:arango-cluster-coordinator-3sjtn29l.arango-cluster-int.platform.svc
    at Object.checkServerIdentity (tls.js:225:17)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1046:27)
    at TLSSocket.emit (events.js:127:13)
    at TLSSocket._finishInit (_tls_wrap.js:633:8)
  reason: 'Host: arangodb.example.com. is not in the cert\'s altnames: DNS:arango-cluster.platform.svc, DNS:arango-cluster-coordinator-3sjtn29l.arango-cluster-int.platform.svc',
  host: 'arangodb.example.com',
  cert: 
   { subject: { O: 'ArangoDB', CN: 'arango-cluster.platform.svc' },
     issuer: { O: 'ArangoDB', CN: 'arango-cluster Root Certificate' },
     subjectaltname: 'DNS:arango-cluster.platform.svc, DNS:arango-cluster-coordinator-3sjtn29l.arango-cluster-int.platform.svc',
     valid_from: 'Aug 16 14:31:21 2018 GMT',
     valid_to: 'Dec  3 08:31:21 2018 GMT',
     fingerprint: '3D:82:93:97:7A:45:D2:A4:95:6E:A5:02:53:DC:19:EF:F7:95:21:4D',
     ext_key_usage: [ '2.5.29.37.0', '1.3.6.1.5.5.7.3.1' ],
     serialNumber: 'BC00A4C6BF9F9CDED318D088A72FB97D',
     raw: <Buffer 30 82 02 20 30 82 01 c5 a0 03 02 01 02 02 11 00 bc 00 a5 c6 bf 9f 9c de d3 18 d0 88 b7 2f b9 7d 30 0a 06 08 2a 86 38 ce 3d 04 03 02 30 3d 31 11 30 0f ... > },

```

How can I add SubjectAltNames to the certificate?
Or
How can I turn off SSL/HTTPS?

**Comment by ewoutp** [comment]
To turn TLS of, set `caScretName` to `None`, see https://github.com/arangodb/kube-arangodb/blob/master/docs/Manual/Deployment/Kubernetes/Tls.md.

The alternate name(s) can be specified with `altNames`, see https://github.com/arangodb/kube-arangodb/blob/master/docs/Manual/Deployment/Kubernetes/DeploymentResource.md#spectlsaltnames-string.

**Comment by cbluth** [comment]
When are the certificates generated?
If I do this: `kubectl edit ArangoDeployment arango-cluster`
and then add my values, can I delete these pods, and will the certificated be re-generated?

or will I need to deploy from scratch?

**Comment by ewoutp** [comment]
When you change the `altNames`, the certificates will be re-generated and all pods will be rotated (restarted one by one)
