### ISSUE TITLE
Istio compatibility issue

### ISSUE THREAD

**Issue by Hugheym** [arangodb/kube-arangodb#260]
I'm trying to deploy on GKE with istio. The problem occurs specifically because of side-car injection, which isn't unique to istio and is part of Envoy. Because an extra container is injected for traffic proxying, the imageID that the operator gets from the imageID pod ends up being that of the side-car. So the image of the container named 'server' in the final deployment becomes istio/proxyv2@sha..., so the container fails to execute arango commands. 
I think I've identified the problem as line 122 in pkg/deployment/images.go: 
```go
imageID := k8sutil.ConvertImageID2Image(pod.Status.ContainerStatuses[0].ImageID)
```
I believe changing this to something like: 
```go
rawImageID := pod.Status.ContainerStatuses[0].ImageID
if len(pod.Status.ContainerStatuses)>1 {
	for _, containerStatus := range pod.Status.ContainerStatuses {
		if strings.Contains(containerStatus.ImageID, "arango"){
				rawImageID = containerStatus.ImageID
	         }
	}
}
imageID := k8sutil.ConvertImageID2Image(rawImageID)
```
should fix this issue.

**Comment by Hugheym** [comment]
I've confirmed that this fixes the issue for me.

**Comment by pamelin** [comment]
Hey @Hugheym are you going to raise PR for this? We are having the same issue.

**Comment by lamai93** [comment]
Hi @Hugheym

Thanks a lot for your improvements. We are using an Apache 2 CLA for ArangoDB and its sub-components, which can be found here: https://www.arangodb.com/documents/cla.pdf

Could you please sign, scan and email it to cla@arangodb.com

Thanks a lot

I prepared a branch for you already: 
https://github.com/arangodb/kube-arangodb/tree/bug-fix/side-car-injection
Please feel free to create a new branch and copy the changes to become the author.

**Comment by Hugheym** [comment]
@lamai93 Thanks! I sent the CLA and created a PR.
