### ISSUE TITLE
What about kubernetes on digital ocean ?

### ISSUE THREAD

**Issue by scroobius-pip** [arangodb/kube-arangodb#317]

**Comment by lamai93** [comment]
Have you tried it and it doesn't work? If so, please provide more information.

**Comment by Siebe** [comment]
Hi. I've successfully deployed a cluster on DigitialOcean. 
One note: if you want to use a loadbalancer with external IP one should force the spec.externalAccess.type to "LoadBalancer". DigitalOcean is a bit slow with creating a loadbalancer for the deployment and thus it seems ArangoDeployment will fall back to NodePort if this setting is not specified.
