### ISSUE TITLE
Setting a password

### ISSUE THREAD

**Issue by Siebe** [arangodb/kube-arangodb#319]
Hello, I'd like to set a password instead of a jwt-secret to secure the database. I used to do this in a docker file by setting the ARANGO_ROOT_PASSWORD environment variable, but I see no option to do this using the ArangoDeployment. Am I missing something? Or might it be possible to secure ArangoDB using the jwt-secret and still be able to log in using the web interface on port 8529?

**Comment by lamai93** [comment]
@Siebe Access via username and password is always possible. Currently there is no option for setting the root password within the ArangoDeployment. However, we are aware of this missing feature and will add it in near future. You can always log in to the web interface with username and password.

Additionally there is `/_open/auth` ([docs](https://docs.arangodb.com/3.4/HTTP/General/#user-jwt-token)) which allows you to generate a JWT token provided a valid username and password.
