### ISSUE TITLE
arango-deployment-operator does not start due to  Liveness probe failed

### ISSUE THREAD

**Issue by cogmeta** [arangodb/kube-arangodb#336]
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  100s               default-scheduler  Successfully assigned default/arango-deployment-operator-65f969fc84-jctgl to olelo
  Normal   Pulled     36s (x3 over 97s)  kubelet, olelo     Container image "arangodb/kube-arangodb@sha256:ae991f94aef9ff25c09b59aa7243155be0ee554a6cc252c59fe3a63d070af42b" already present on machine
  Normal   Created    36s (x3 over 96s)  kubelet, olelo     Created container
  Normal   Started    36s (x3 over 96s)  kubelet, olelo     Started container
  Normal   Killing    36s (x2 over 66s)  kubelet, olelo     Killing container with id docker://operator:Container failed liveness probe.. Container will be killed and recreated.
  Warning  Unhealthy  17s (x8 over 87s)  kubelet, olelo     Liveness probe failed: Get https://192.0.0.8:8528/health: dial tcp 192.0.0.8:8528: connect: connection refused
  Warning  Unhealthy  12s (x6 over 82s)  kubelet, olelo     Readiness probe failed: Get https://192.0.0.8:8528/ready/deployment: dial tcp 192.0.0.8:8528: connect: connection refused

**Comment by lamai93** [comment]
Please provide more information. Which Platform do you use? Which version of the operator do you use? Which version of arangodb do you use?
