### ISSUE TITLE
Cheapest configuration

### ISSUE THREAD

**Issue by janat08** [arangodb/kube-arangodb#354]
Like from half a year ago setting this up on GCE it would've cost like 100 usd, is there a way to reconfigure it to run cheaper?

**Comment by kvahed** [comment]
Hi @janat08 ,

GKE is of course not exactly the cheapest cloud offering on the market. Even if you tried to go with say 3 1CPU units, the costs wouldn't necessarily be much lower. And that is of course the absolute minimum requirement. In any case, we have not tried to explore the lowest possible requirements on every cloud platform. Our goal was merely to provide a simple path to initial success. This setup will not even get near production grade setup, as the IO per second would limit the bandwidth to the cluster drastically. Does that make sense?
 
Kind regards,
Kaveh
