### ISSUE TITLE
Readiness probe failed / Failed Scheduling

### ISSUE THREAD

**Issue by liuwenzhi0318** [arangodb/kube-arangodb#363]
Problem
## kubectl describe pod example-arangodb-cluster-sngl-z0ookp05-949a10
 Readiness probe failed: HTTP probe failed with statuscode: 503

Configuration
---
apiVersion: "storage.arangodb.com/v1alpha"
kind: "ArangoLocalStorage"
metadata:
  name: "example-arangodb-storage"
spec:
  storageClass:
    name: my-local-ssd
  localPath:
  - /mnt/big-ssd-disk

---
apiVersion: "database.arangodb.com/v1alpha"
kind: "ArangoDeployment"
metadata:
  name: "example-arangodb-cluster"
spec:
  mode: Single
  environment: Production
  image: "arangodb/arangodb:3.3.4"
  single:
    resources:
      requests:
        storage: 10Gi
    storageClassName: my-local-ssd
  auth:
    jwtSecretName: None

**Comment by liuwenzhi0318** [comment]
## ls /mnt/big-ssd-disk/

Directory empty

**Comment by maierlars** [comment]
@liuwenzhi0318 `image: "arangodb/arangodb:3.3.4"` this is a very old version. Please try `image: "arangodb/arangodb:3.4.4"`.

**Comment by liuwenzhi0318** [comment]
Thank you ！！  After being changed to 3.4.4
Because I am a test machine and only have one node, I think it seems to need 3 nodes to report an error in the log?

Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  13s (x6 over 2m37s)  default-scheduler  0/3 nodes are available: 1 node(s) had taints that the pod didn't tolerate, 2 node(s) were unschedulable.

**Comment by maierlars** [comment]
No, the Pod can not be scheduled since no node is available: `1 node(s) had taints that the pod didn't tolerate, 2 node(s) were unschedulable.` Please check your nodes.

**Comment by liuwenzhi0318** [comment]
Thank you
