### ISSUE TITLE
How to Backup and Import Data in cluster Mode Started. Do you have any relevant documents?

### ISSUE THREAD

**Issue by liuwenzhi0318** [arangodb/kube-arangodb#365]
How to Backup and Import Data in cluster Mode Started. Do you have any relevant documents?

**Comment by maierlars** [comment]
Currently the way of doing backups is [Arangodump](https://docs.arangodb.com/3.4/Manual/Programs/Arangodump/). To restore use [Arangorestore](https://docs.arangodb.com/3.4/Manual/Programs/Arangorestore/). Connect to your cluster using the external access.
