### ISSUE TITLE
foxx service

### ISSUE THREAD

**Issue by adian** [arangodb/kube-arangodb#400]
How can I deploy arangodb with Foxx service? On docker, I run my script which runs arango and installs my foxx service.

**Comment by maierlars** [comment]
This is currently not possible using the `ArangoDeployment` resource. You can install your foxx service after you have deployed the cluster.

**Comment by adian** [comment]
Is there a possibility to install it from inside of the image? I have arango image with `foxx-service.zip` inside.

**Comment by adian** [comment]
Is there a way to automate installing foxx to cluster?
