### ISSUE TITLE
Support installation via kustomize

### ISSUE THREAD

**Issue by jaredpetersen** [arangodb/kube-arangodb#402]
The ArangoDB operator currently supports installation via kubectl and Helm. It would also be useful if installation could be provided by [Kustomize](https://kustomize.io/). It offers customization functionality similar to Helm but doesn't require you to tear up your YAML files with templating.

Kustomize is now packaged into kubectl as of version 1.14 via `kubectl apply -k`. It's supported out of the box without the need to install another tool and seems to be the direction the "official" Kubernetes community is going.

**Comment by ajanikow** [comment]
Hello!

Change will be in next release, already in master.

Best Regards,
Adam.
