### ISSUE TITLE
MemberOfCluster condition isn't updated 

### ISSUE THREAD

**Issue by Robert-Stam** [arangodb/kube-arangodb#422]
When a server becomes member of a cluster it's not always populated correctly in the status of a arangodeployment (CRD object). 
See attached the log of the role=leader operator and the YAML od the deployment

[log-ado.txt](https://github.com/arangodb/kube-arangodb/files/3421298/log-ado.txt)
[arango-depl.yaml.txt](https://github.com/arangodb/kube-arangodb/files/3421306/arango-depl.yaml.txt)

**Comment by Robert-Stam** [comment]
In which version is this resolved?

**Comment by maierlars** [comment]
https://github.com/arangodb/kube-arangodb/pull/425

**Comment by Robert-Stam** [comment]
That’s the checkin/merge to master, I mean 0.3.13 (expected Tomorrow )
