### ISSUE TITLE
Change root password if secret for it changes

### ISSUE THREAD

**Issue by ewoutp** [arangodb/kube-arangodb#429]
I expect the root password of the database to reflect the current value of the password field of the secret specified in `spec.bootstrap.passwordSecretNames.root`.
This means that if the password in the secret changes, the root password in the database should change accordingly and let me know that it did so.

If the secret (identified by above field) is not there, I expect nothing to happen.

The reasoning behind this is that I want to be able to remove the secret as soon as bootstrapping has finished in order to minimise exposure to this secret.

**Comment by maierlars** [comment]
Allow to delete the secret as well.

**Comment by informalict** [comment]
it is done
