### ISSUE TITLE
When using VolumeClaimTemplates changing of StorageClass is not possible

### ISSUE THREAD

**Issue by maierlars** [arangodb/kube-arangodb#437]

**Comment by informalict** [comment]
1) Two StorageClass had been created: storage (default), storage2.

2) Apply the below example into the kubernetes cluster:
 
apiVersion: "database.arangodb.com/v1alpha"
kind: "ArangoDeployment"
metadata:
  name: chaos
spec:
  imagePullPolicy: Always
  tls:
    caSecretName: None
    altNames: ["chaos.havefuninthe.net"]
  mode: Cluster
  locallyAttachedVolumes: false
  environment: Production
  license:
    secretName: arangodb-license-key
  image: arangodb/arangodb:3.3.17
  agents:
    count: 3
    storageClassName: standard
  dbservers:
    count: 2
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 8Gi
        volumeMode: Filesystem
    storageClassName: standard2
  coordinators:
    count: 3

3) Wait for five PVC (2 for dbservers, 3 for agents)

4) Change spec.dbservers.storageClassName to standard

5) Two dbservers have got new PVC created according to the new StorageClass (standard)

**Comment by informalict** [comment]
Try with volumeClaimTemplate and storageClass inside this object
