### ISSUE TITLE
TLS server certificates must rotate when non-owned root CA has changed

### ISSUE THREAD

**Issue by ewoutp** [arangodb/kube-arangodb#439]
Context: 

We're building our own Secrets with the root CA for TLS.
The operator uses this secret (which is knows that it does not own it) to create individual TLS certificates for each server.

We now want to change this root CA.
The expected result is that the operator detects a changes and start to create new TLS certificates for all servers (and rotate these servers). This is know to have a small downtime.

The actual result is log messages like this: `Condition SecretsChanged is true. Revert secrets before we can continue`

**Comment by maierlars** [comment]
Am I missing something or why do you expect a down time?

**Comment by ewoutp** [comment]
When the root CA changes, there is a short time between then and the time that all servers get their new TLS certificates.
In that short period, servers will not be able to talk to all other servers because they cannot trust the TLS certificate.

**Comment by maierlars** [comment]
There is no TLS certificate verification in arangodb.

**Comment by ewoutp** [comment]
Not sure if I should answer "good" or "bad". But it does not change the feature request.

**Comment by ajanikow** [comment]
Hello!

It is covered by latest Operator. For Community rotate is done with restarts behind, for Enterprise in runtime.
