### ISSUE TITLE
Write-write conflict (while executing)

### ISSUE THREAD

**Issue by Fruchtgummi** [arangodb/kube-arangodb#459]
Arango 3.5.0
Cluster 3-Coordinator, 3 DB-Servers
On: Amazon EKS-Cluster 3 Nodes, t3.medium

Error: 

"AQL: Error message received from cluster node 'PRMR-sbosa6ad': write-write conflict (while executing)"

after this error terminate one DB server.

**Comment by maierlars** [comment]
This is unrelated to the Kubernetes operator but instead a database issue. Please file future issues here: https://github.com/arangodb/arangodb/issues.
