### ISSUE TITLE
go mod fails on go 1.13 because of invalid pseudo-version

### ISSUE THREAD

**Issue by Skarlso** [arangodb/kube-arangodb#462]
Once arango switches to go 1.13 the build will fail with this error:

```
go: github.com/coreos/prometheus-operator@v0.31.1 requires
        github.com/prometheus/prometheus@v2.9.2+incompatible requires
        k8s.io/client-go@v2.0.0-alpha.0.0.20181121191925-a47917edff34+incompatible: invalid pseudo-version: preceding tag (v2.0.0-alpha.0) not found
```

This related to this:

https://github.com/golang/go/issues/33546 from go.

And here is the related prometheus issue for it:

https://github.com/prometheus/prometheus/issues/6048

TL;DR arango needs to get the commit ID instead of the version because prometheus doesn't care about go's API compatilibity restrictions.

**Comment by Skarlso** [comment]
Ah, another one:

https://github.com/kubernetes/client-go/issues/670

Which means the official standpoint is:

> Kubernetes only supports go 1.12 for now. It's a known issue that there are several problems with > 1.13, see kubernetes/kubernetes#78845 (comment) for more details.

**Comment by bcmills** [comment]
> Which means the official standpoint is:

Note also https://github.com/kubernetes/kubernetes/issues/79384#issuecomment-505725449:

> k8s.io/kubernetes is not primarily intended to be consumed as a module. Only the published subcomponents are (and go get works properly with those).
>
> If you want to consume k8s.io/kubernetes as a module, you'd probably need to add require directives for matching versions of all of the subcomponents, rather than using go get

So it's a bit misleading to say that Kubernetes only supports Go 1.12. Rather, Kubernetes only supports _use of their published subcomponents_ on 1.13, and presumably only at tagged releases, and still uses 1.12 internally.

**Comment by Skarlso** [comment]
Hey, thanks for chiming in! 😊

Yes that's true. But also Kube is facing some other issues involved in switching to 1.13. But that's fine. Arango is still using 1.14 or so so its not like this is next week's trouble.

**Comment by RoyCrivolotti** [comment]
I'm facing the issue above myself right now! My Dockerfile used to work fine, but now I'm getting the following error. Maybe you could give me a hand pointing out how I might go about fixing the compatibility issue I seem to be facing.

```
Step 12/14 : RUN go get -d ./... &&     go build -o operator &&     cp operator /bin/operator
 ---> Running in 911a78212ed5
go: github.com/prometheus/prometheus@v2.9.2+incompatible requires
        k8s.io/client-go@v2.0.0-alpha.0.0.20181121191925-a47917edff34+incompatible: invalid pseudo-version: preceding tag (v2.0.0-alpha.0) not found
The command '/bin/sh -c go get -d ./... &&     go build -o operator &&     cp operator /bin/operator' returned a non-zero code: 1
```

This is my Dockerfile

```
FROM golang:alpine

RUN set -ex && \
    apk update && \
    apk -U upgrade && \
    apk add curl && \
    apk add git

RUN mkdir -p /operator && \
    mkdir -p /temp

RUN curl -L -k https://github.com/coreos/prometheus-operator/archive/v0.31.1.tar.gz > operator.tar.gz && \
    tar -xzvf operator.tar.gz --strip-components=1 -C /operator

RUN rm operator.tar.gz

COPY promcfg.go /temp/promcfg.go 

WORKDIR /temp

RUN yes | cp -rf promcfg.go /operator/pkg/prometheus/promcfg.go

WORKDIR /operator/cmd/operator

RUN go get -d ./... && \
    go build -o operator && \
    cp operator /bin/operator

RUN rm -rf /temp && \
    rm -rf /operator

ENTRYPOINT ["/bin/operator"]
```

**Comment by bcmills** [comment]
@RoyCrivolotti, per https://golang.org/doc/go1.13#version-validation, try (in your `go.mod` file):

```
replace k8s.io/client-go v2.0.0-alpha.0.0.20181121191925-a47917edff34+incompatible => k8s.io/client-go a47917edff34
```

and then run `go mod tidy` or similar to resolve that to a corrected pseudo-version.

**Comment by RoyCrivolotti** [comment]
IDK exactly where that line is, aka what file it's in, so I'll comment the layers crashing the build, do the rest of the work work, get into the container with bash, and search in the uncompressed files for the line you say with `grep` or something. Thanks a lot for your help 😄

**Comment by bcmills** [comment]
No, I mean literally add that line somewhere in your module's `go.mod` file. 😉

**Comment by RoyCrivolotti** [comment]
Oh hahaha my bad, yeah that fixed it 100%. I didn't know where the go.mod file would be since I've never used this, so I just wen into the container with `busybox sh` when running the container to see the path to the file, and then performed a patch and run the `tidy` command. Seriously, thanks a lot!
