### ISSUE TITLE
ArangoLocalStorage will never provision a PVC with new ServiceAccount setup (>= 0.3.16 < 0.4.1)

### ISSUE THREAD

**Issue by monotykamary** [arangodb/kube-arangodb#467]
Tested on versions 0.3.16 and 0.4.0 on a freshly spun up single node cluster with:
- kubeadm (tainted)
- rke (with bound /mnt:/mnt:rshared)

Resources used and tested on `default` and custom namespace:

```
kubectl apply -f https://raw.githubusercontent.com/arangodb/kube-arangodb/0.3.16/manifests/arango-crd.yaml
kubectl apply -f https://raw.githubusercontent.com/arangodb/kube-arangodb/0.3.16/manifests/arango-storage.yaml

kubectl apply -f https://raw.githubusercontent.com/arangodb/kube-arangodb/0.4.0/manifests/arango-crd.yaml
kubectl apply -f https://raw.githubusercontent.com/arangodb/kube-arangodb/0.4.0/manifests/arango-storage.yaml
```

---

Applying just the CRD and arango-storage-operator, any workload resource that creates a PVC and requests for the operator's storageClass will forever pend as the PVC will never be claimed. Logging the operator gives us these errors:

```
2019-10-12T11:56:26Z ??? E1012 11:56:26.583411       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.PersistentVolumeClaim: persistentvolumeclaims is forbidden: User "system:serviceaccount:default:arango-storage-operator" cannot list resource "persistentvolumeclaims" in API group "" at the cluster scope component=klog operator-id=sg7vr
2019-10-12T11:56:26Z ??? E1012 11:56:26.583411       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.PersistentVolumeClaim: persistentvolumeclaims is forbidden: User "system:serviceaccount:default:arango-storage-operator" cannot list resource "persistentvolumeclaims" in API group "" at the cluster scope component=klog operator-id=sg7vr
2019-10-12T11:56:26Z ??? E1012 11:56:26.583411       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.PersistentVolumeClaim: persistentvolumeclaims is forbidden: User "system:serviceaccount:default:arango-storage-operator" cannot list resource "persistentvolumeclaims" in API group "" at the cluster scope component=klog operator-id=sg7vr
```

By appending the following API groups to operator's ClusterRole (as existed in the versions <=0.3.14), PVC gets claimed and pods run normally:

```
...
 apiVersion: rbac.authorization.k8s.io/v1
 kind: ClusterRole
 metadata:
     name: arango-storage-operator-rbac-storage
     namespace: default
     labels:
         app.kubernetes.io/name: kube-arangodb
         helm.sh/chart: kube-arangodb-0.4.0
         app.kubernetes.io/managed-by: Tiller
         app.kubernetes.io/instance: storage
         release: storage
 rules:
     - apiGroups: ["apiextensions.k8s.io"]
       resources: ["customresourcedefinitions"]
       verbs: ["get"]
+    - apiGroups: [""]
+      resources: ["persistentvolumes", "persistentvolumeclaims", "endpoints", "events", "services"]
+      verbs: ["*"]
     - apiGroups: [""]
       resources: ["namespaces", "nodes"]
       verbs: ["get", "list"]
     - apiGroups: ["storage.k8s.io"]
       resources: ["storageclasses"]
       verbs: ["*"]
     - apiGroups: ["storage.arangodb.com"]
       resources: ["arangolocalstorages"]
       verbs: ["*"]
...
```

This issue does not appear for versions <= 0.3.14.

**Comment by ex-nerd** [comment]
If I'm reading the files properly, I think this has now been fixed in `0.4.1`, but I'm still seeing failures when running things in GKE.

**Comment by ajanikow** [comment]
Hello!

Can you provide me more details where are you able to see this kind of errors?

In Kube-ArangoDB Operator we have privileges for PVC and list nodes in the RBAC configuration.

I was unable to find usage of the K8S CSR in the Operator code.

Best Regards,
Adam Janikowski.

**Comment by ex-nerd** [comment]
@ajanikow It looks like my errors were related to some changes in k8s permissions that blocked access to creating a storage mount under `/mnt/*`. The stackdriver logs (my go-to place for logs in gcloud) seem to be a red herring or at least not exposing the actual error message.  I eventually found the helpful permissions errors under `kubectl get events` and was able to get things to spin up after moving my mounts to `/var/lib/*`.

I've filed a separate issue at #479, but that seems unrelated to this.

**Comment by monotykamary** [comment]
I haven't had time to test the new changes on 0.4.1 yet, but I'm pretty sure it will work.

What I'm more perplexed by is why the service account can't list PVCs when they are namespace bound and are clearly specified in the Role resource (in 0.3.16, 0.40). It could be a problem with just `persistentvolumes` (as its the only cluster-scoped object here), but then it should show up as a mount fail or be a more relevant forbidden error.

I honestly think we can just get away with listing only the `persistentvolumes` resource in the ClusterRole since the rest are properly namespace-scoped, but I'll need to check on a test cluster when I get to it.

**Comment by monotykamary** [comment]
0.4.1 works great, haven't run into any problems so far (at least not related to this issue).

However, I've tested with restricting the cluster role with just `persistentvolumes` and it failed. It may be that the operator is also requesting resource listing for `persistentvolumeclaims` outside of the namespace; I haven't dug too deep.
