### ISSUE TITLE
arangodb k8 mode single failing

### ISSUE THREAD

**Issue by Taijo** [arangodb/kube-arangodb#489]
Hi, 
did someone succeed to use arangodb in mode : single ? (deployment) 
-> my operator can't communicate with my pod arangodb in mode : single server

2019-10-22T11:59:14Z DBG Failed to get version error="Get https://arango2.default.svc:8529/_api/version: dial tcp 10.3.117.111:8529: i/o timeout" action-id=QRQvcnEpwcv6olcO action-type=WaitForMemberUp component=deployment deployment=arango2 group=single member-id=SNGL-jjrmjzv4 operator-id=cj2wt plan-len=1

-> the operator pod keep shutting down the arango single server pod each time

logs details
[arango_operator_logs.txt](https://github.com/arangodb/kube-arangodb/files/3766287/arango_operator_logs.txt)
[arango_single_server_pod_log.txt](https://github.com/arangodb/kube-arangodb/files/3766288/arango_single_server_pod_log.txt)

Other informations
kubernetes v1.5.5
arango custom resources 0.4.1

**Comment by ajanikow** [comment]
Hello!

We are checking ArangoDB single-server deployments as part of the scope of our tests.

According to the error log from the operator, I see it can be a networking issue. Can you check if you have a connection between pods?

Can you share with me more details about `arango2` service and ArangoDB pods? Also, it would be nice if you can share with me your `ArangoDeployment` object details.

Best Regards,
Adam Janikowski.

**Comment by ajanikow** [comment]
Hello!

Will close this issue. Please, reopen it if you will face this problem again.

Best Regards,
Adam Janikowski.
