### ISSUE TITLE
Documentation issues for config and secrets

### ISSUE THREAD

**Issue by averri** [arangodb/kube-arangodb#504]
The document here needs improvement:
https://github.com/arangodb/kube-arangodb/blob/master/docs/Manual/Deployment/Kubernetes/ConfigAndSecrets.md

The doc says: "_All commandline options of arangod (and arangosync) are available by adding options to the `spec.<group>.args` list of a group of servers._"

What is the `<group>`? Please improve the documentation giving a clear example.
Suggestion: how to add the flag: 

> --server.authentication <boolean>                            enable authentication for ALL client requests (default: true)

**Comment by averri** [comment]
After a lot of research, I have found this document: 
https://www.arangodb.com/docs/stable/deployment-kubernetes-deployment-resource.html

... which contains the answer to my question above. It would be great to put the reference in the aforementioned document.

**Comment by ajanikow** [comment]
Hello!

Arango Doc clarified.

Best Regards,
Adam.
