### ISSUE TITLE
Backup failed

### ISSUE THREAD

**Issue by waclawikj** [arangodb/kube-arangodb#507]
When I am creating backup resource i get error:
`Transiting from Create to Failed with error: Transiting from Create to Failed: unknown path '/_admin/backup/create' `

Isn't this path only for Hot Backups (which comes only in Enterpise Edition, when I am using Community Edition)?

**Comment by xelik** [comment]
I have the same issue. If this is only in Enterprise Edition, then how can I do backups at k8s cluster in free edition ??

**Comment by ajanikow** [comment]
Hello!

Backup is part of Enterprise Edition.

In Community Edition you still can use `arangodump` - https://www.arangodb.com/docs/stable/programs-arangodump.html - but it is not supported by Operator.

Best Regards,
Adam Janikowski

**Comment by waclawikj** [comment]
Ok, so can you add information in documentation in Kubernetes section about backups (backup, backup resource etc) mentioning that it works only with Enterprise Edition?

**Comment by ajanikow** [comment]
Hello!

It is part now of documentation.

Closing issue.

Best Regards,
Adam.

**Comment by djmcgreal-cc** [comment]
Where exactly do you think you documented this?
This repository's README links to https://www.arangodb.com/docs/stable/deployment-kubernetes.html which doesn't mention it, nor does the documentation for the https://www.arangodb.com/docs/stable/deployment-kubernetes-backup-resource.html itself. Nor does https://www.arangodb.com/why-arangodb/arangodb-enterprise/ or https://www.arangodb.com/subscriptions/.

I think you'll agree, that the error message from the operator is also less than helpful.

**Comment by canthonyscott** [comment]
Its two years later, I still do not see this listed in any documentation

**Comment by WoodyWoodsta** [comment]
Came here looking for it as well.

**Comment by thorleifjacobsen** [comment]
Same problem.. 

```
2022-10-14T10:18:39Z DBG Refreshing database objects operator-id=xg6z4
{"level":"error","error":"unknown path '/_admin/backup/list'","time":"2022-10-14T10:18:39Z","message":"Unable to refresh database objects"}
```

Adding this so google can find this thread for others that get this exact error. And the answer seems to be "Not for community edition"
