### ISSUE TITLE
ArangoDeployment fails when deploying to namespace with Istio mTLS enabled.

### ISSUE THREAD

**Issue by fico-jessecarroll** [arangodb/kube-arangodb#510]
ArangoDeployment fails when deploying to namespace with Istio mTLS enabled.  More than likely this is due to Kube-Arango using own certs between operators/agents.  Is it possible to use Istio certs instead?  If so, maybe adding documentation on how this would be achieved would be helpful.  Steps to reproduce:
1. Install Istio with strict mTLS enabled.
2. Install kube-arango operator.  Only 1 of N replicas startup.  The others fail with 'http: TLS handshake error from 127.0.0.1:32856: EOF' .

**Comment by ajanikow** [comment]
Hello!

Docs on Arango Doc page clarified.

Best Regards,
Adam.

**Comment by fico-jessecarroll** [comment]
Can you point out where this clarification is?
