### ISSUE TITLE
Optimization rule splice-subqueries problem

### ISSUE THREAD

**Issue by energia-europa** [arangodb/kube-arangodb#513]
We run this query on arangodb 3.5.3 and work it. Instead not work on arangodb 3.6 that implements "splice-subqueries" optimization rule.

LET ii509rym = (
  LET multiple_expressions_routes_result = (
    FOR iteration IN 0..10
      LET from_aggregation = (FOR ii IN 0..30 RETURN ii)
      RETURN from_aggregation
   )
   RETURN multiple_expressions_routes_result
)
RETURN ii509rym

**Comment by ajanikow** [comment]
Hello!

It is more like ArangoDB bug, not related to ArangoDB Operator. Can you create issue on ArangoDB project (https://github.com/arangodb/arangodb/issues) providing more details? Error message, used image, provider and OS.

Best Regards, 
Adam Janikowski.

**Comment by ajanikow** [comment]
Hello!

Closing issue.

Best Regards,
Adam.
