### ISSUE TITLE
Helm "UPGRADE FAILED: rendered manifests contain a new resource that already exists." errors

### ISSUE THREAD

**Issue by jspc** [arangodb/kube-arangodb#521]
Hi all,

I've got a CI job somewhere which deploys arangodb to a Kubernetes cluster. My CI job includes the two helm commands:

```bash
helm upgrade --install --namespace=some-namespace arangodb-crd https://github.com/arangodb/kube-arangodb/releases/download/0.4.3/kube-arangodb-crd-0.4.3.tgz
helm upgrade --install --namespace=some-namespace arangodb https://github.com/arangodb/kube-arangodb/releases/download/0.4.3/kube-arangodb-0.4.3.tgz --set operator.features.storage=true
```

The first runs fine (though it increments the revision number each time, which I'd expect it not to do, but I think that's a helm thing). The second command gives me:

```
Error: UPGRADE FAILED: rendered manifests contain a new resource that already exists. Unable to continue with update: existing resource conflict: kind: CustomResourceDefinition, namespace: , name: arangolocalstorages.storage.arangodb.com
```

Has anybody seen this before? Am I doing something stupid? I would expect helm and/or the CRD to not try and recreate things which already exist.

**Comment by ajanikow** [comment]
Hello!

Do you have installed this chart in any other namespace? CRD is non-namespaced resource and name needs to be constant (so it cannot be generated for specific installation)

Best Regards,
Adam Janikowski

**Comment by iMoses** [comment]
@ajanikow having the same issue, version 1.0.2 on AKS, on a clean cluster with a clean install

**Comment by iMoses** [comment]
Looks like `kube-arangodb/templates/backup-operator/cluster-role-binding.yaml` has the wrong `name`
