### ISSUE TITLE
Can I set external access type to ClusterIP

### ISSUE THREAD

**Issue by reidlai** [arangodb/kube-arangodb#542]
Because I am not exposing ArangoDB for external use, all access can only go through POD, how can i set externalAccess.type to ClusterIP of ArangoDeployment ?

**Comment by lnogol** [comment]
```yaml
  externalAccess:
    type: None
```

ClusterIP service is then created with the same name as the `ArangoDeployment` resource

**Comment by ajanikow** [comment]
Hello!

All modes also described in the documentation: https://www.arangodb.com/docs/stable/deployment-kubernetes-deployment-resource.html#specexternalaccesstype-string

Best Regards,
Adam Janikowski.

**Comment by ajanikow** [comment]
Hello!

Issue will be closed.

Best Regards,
Adam Janikowski.
