### ISSUE TITLE
Create a chart repository

### ISSUE THREAD

**Issue by iMoses** [arangodb/kube-arangodb#562]
according to this: https://helm.sh/docs/topics/chart_repository/
all you need to do is have an updated `index.yaml` file with all releases defined in it, and t can be anywhere from a static server to github-page.

this will make installing and managing dependencies of kube-arangodb much easier!

**Comment by mysticaltech** [comment]
Yes exactly, and this can make the whole process really trivial https://github.com/helm/chart-releaser! Also, it would allow **helm upgrade** to work!

**Comment by mysticaltech** [comment]
And that's the exact methodology right there! https://harness.io/blog/helm-chart-repo/

**Comment by mysticaltech** [comment]
@ewoutp @ajanikow @maierlars This is very low-hanging fruit, IMHO ripe for picking! It will close 3 issues and will make this repo even more awesome by having automated helm support! 

The blog link above exposes the method that uses **Github actions and pages to automate everything**, it can be done in less in 15 minutes (hopefully)! 🙏

**Comment by informalict** [comment]
Hello @mysticaltech 

Please use the following commands to use the kube-arangodb chart repo:

helm repo add arangodb-helm-charts https://arangodb.github.io/kube-arangodb

helm install crd arangodb-helm-charts/kube-arangodb-crd
helm install crd arangodb-helm-charts/kube-arangodb

**Comment by nikita-vanyasin** [comment]
This ticket can be closed now: we switched on the automatic update of Helm registry again.
