### ISSUE TITLE
Helm installation under the same name in different namespace fails

### ISSUE THREAD

**Issue by nirroz93** [arangodb/kube-arangodb#575]
Starting with Helm 3 a release is namepsace scoped.

Currently, installation with the same release name for the operator fails.

helm install arango-operator https://github.com/arangodb/kube-arangodb/releases/download/1.0.3/kube-arangodb-1.0.3.tgz 
NAME: arango-operator
LAST DEPLOYED: Sun Jun  7 16:53:31 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
You have installed Kubernetes ArangoDB Operator in version 1.0.3

To access ArangoDeployments you can use:

kubectl --namespace "default" get arangodeployments

nirr ~ (devops.k8s.local )$ kubectl create namespace namespace2
namespace/namespace2 created
nirr ~ (devops.k8s.local )$ helm install arango-operator https://github.com/arangodb/kube-arangodb/releases/download/1.0.3/kube-arangodb-1.0.3.tgz  -n namespace2
Error: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "arango-arango-operator-operator-rbac-deployment" in namespace "" exists and cannot be imported...

This is becuase of ClusterRole that is not namespace scoped (why use clsuter role if it's namespace scoped?) so it must be unique. 

Is there any way to make it work? Until https://github.com/arangodb/kube-arangodb/issues/401 is solved we must install multiple operators in many namespaces, so it would be nice if it was at least in the same name.

**Comment by ajanikow** [comment]
Hello!

Name field of helm install is part of resource names - if you change name you will be able to install it in multiple namespaces.

Best Regards,
Adam.

**Comment by ajanikow** [comment]
Hello!

Change will be in next release, already in master.

Best Regards,
Adam.
