### ISSUE TITLE
Support for ARANGODB_OVERRIDE_DETECTED_TOTAL_MEMORY

### ISSUE THREAD

**Issue by weisdd** [arangodb/kube-arangodb#579]
As you know, normally, ArangoDB installations in a containerized environment require some memory footprint tuning due to the fact that the server doesn't rely on cgroups limits when it's calculating sizes for its multiple buffers.

In 3.6.2.1, ARANGODB_OVERRIDE_DETECTED_TOTAL_MEMORY ("Allow to override the detected total amount of memory via an environment variable", e.g. in master the code can be found [here](https://github.com/arangodb/arangodb/blob/72fa16dbb3c56fed4b473e32e57b6f5bee01c42a/lib/Basics/PhysicalMemory.cpp#L98)) env was introduced, which is a great and a long-awaited feature.
It'd be great to either have an option to define our own set of extra environment variables in CRD (like in #396), or kube-arangodb should simply inject ARANGODB_OVERRIDE_DETECTED_TOTAL_MEMORY by default.

Thanks!

**Comment by ajanikow** [comment]
Hello!

This is propably what you are looking for: https://www.arangodb.com/docs/stable/deployment-kubernetes-deployment-resource.html#specgroupoverridedetectedtotalmemory-bool

It will be set to currently set limits for your group members.

Best Regards,
Adam.

**Comment by weisdd** [comment]
Hello @ajanikow,

Oh, I have missed this parameter, because, while searching, I was relying only on "env" keyword :)
Thanks for pointing it out! - That's exactly what I was looking for.
