### ISSUE TITLE
Arango Co-Ordinator:- Transaction roll back failures with Precondition Failed. [DB version:3.6.1]

### ISSUE THREAD

**Issue by mragupat** [arangodb/kube-arangodb#598]
**Issue:**
Transaction Rollback failures non stop.

K8s Cluster [Size:-]
5-crdn, 3-agnt, 8-prmr

pod_name: pers-arangodb-crdn-algtqubm-230f5a

**2020-07-15T14:56:25Z [1] WARNING [b47aa] {cluster} failed to cancel creation of database tenant_xxxxx_xxxx with error Precondition Failed. Retrying.**

![Screen Shot 2020-07-15 at 9 59 36 AM](https://user-images.githubusercontent.com/16086660/87561732-b3a1e080-c682-11ea-8e70-76cba17b3c1e.png)

**Comment by ajanikow** [comment]
Hello!

It sounds like ArangoD Warning, not related to Kube-ArangoDB. Can you create issue under https://github.com/arangodb/arangodb/issues ?

Best Regards,
Adam Janikowski.

**Comment by ajanikow** [comment]
Hello!

Issue is related to ArangoDB Coordinator - will create issue in ArangoDB issues.

Best Regards, 
Adam Janikowski.
