### ISSUE TITLE
Is there any viable way of setting timezone for ArangoDB k8s deployment?

### ISSUE THREAD

**Issue by zhuli19901106** [arangodb/kube-arangodb#602]
I know that <b>setting the TZ variable and mounting /etc/localtime </b>is the standard practice for configuring timezone.

It's easily attainable with docker run, but how do I do it when I deploy ArangoDB using CRD from kube-arangodb?

Please help, any advice is appreciated.

**Comment by zhuli19901106** [comment]
https://developpaper.com/pod-preset-plays-k8s-container-time-zone-automatic-configuration/

**Comment by ajanikow** [comment]
Hello!

You can use, for example, environment variable from ArangoDeployment: https://github.com/arangodb/kube-arangodb/blob/master/pkg/apis/deployment/v1/server_group_spec.go#L64 (1.0.4+)

or PodPreset to force use of labels (app=arangodb) - both solutions will work.

Best Regards,
Adam Janikowski.

**Comment by zhuli19901106** [comment]
I'll see about the env solution.
I've already tried PodPreset with matching label, it worked as expected.

Thanks for the reply, much appreciated : )
