### ISSUE TITLE
how to pass rocksdb configurations using k8s?

### ISSUE THREAD

**Issue by effesessa** [arangodb/kube-arangodb#603]
Hello everyone, 
please help me!

I need to configure some of these parameters (https://www.arangodb.com/docs/stable/programs-arangod-rocksdb.html) as time degradation occurs with batch writing processes.
I also accept possible suggestions of how to set these parameters.

Thanks

**Comment by ajanikow** [comment]
Hello!

According to docs: https://www.arangodb.com/docs/stable/deployment-kubernetes-deployment-resource.html#specgroupargs-string

You can pass them for each group thru ArangoDeployment yaml.

I will close this task as duplicated https://github.com/arangodb/arangodb/issues/12302

Best Regards,
Adam.
