### ISSUE TITLE
For ArangoDB cluster on k8s, deleted pods will be left as "missing nodes" on WebUI when redeployment is done

### ISSUE THREAD

**Issue by zhuli19901106** [arangodb/kube-arangodb#604]
## My Environment
- ArangoDB Version: 3.6
- Storage Engine: RocksDB
- Deployment Mode: Cluster
- Deployment Strategy: ArangoDB Kubernetes Operators
- Configuration: hostPath pv and node affinity for storage
- Infrastructure: 3 private servers
- Operating System: Centos 7
- Resources: 48\~96G RAM, 16\~32 CPUs each, enough for basic testing
- Docker image: official Docker library from Docker Hub

I have designed an install plan and an equivalent uninstall version for **ArangoDB k8s cluster mode deployment**.

It works as expected, and data paths are fixed for each k8s node. Left intact when service is uninstalled, so that they're mounted again next time.

For instance, I got **3 k8s nodes** for ArangoDB and try the **install/clean process 4 times** with success.

Each node is supposed to have one agent, one coordinator, and one DB server.

Now there's a small problem:
- The number of coordinators in the dashboard is 3/12
- In the "cluster" page, the metrics won't load, I believe it's trying to visit the already gone pods.
- In the “Nodes” page, I can't really click the "abort" button, it doesn't seem to work.

Question is:
- Will that finally be put right without intervention?
- Or could I do something with minimal efforts to make it 3/3 again?
- If it keeps the deleted pods as records, does it affect normal usage of the DB?

It looks like this now.
![image](https://user-images.githubusercontent.com/5689302/88651302-1de36800-d0fc-11ea-9581-bc51533c7276.png)
![image](https://user-images.githubusercontent.com/5689302/88651487-466b6200-d0fc-11ea-986e-8fd30f0b422b.png)

It's operational, but the dashboard can't display due to missing pods.

Thanks in advance.

**Comment by zhuli19901106** [comment]
Later I found out that the key problem was that the agency nodes won't work when redeployed using existing data from previously deleted pods.

![image](https://user-images.githubusercontent.com/5689302/88678925-8729a200-d121-11ea-845b-1981d871f4de.png)

The names in red boxes above were from the first clean deployment, they're long gone.

![image](https://user-images.githubusercontent.com/5689302/88679283-dc65b380-d121-11ea-96c8-115f4fa03ddd.png)

DB server were able to start as they communicate with one of the agencies.<br>
But the problem is that agencies wouldn't recognize each other because they all remember the old names.<br>
Thus DB servers couldn't find a working group of agencies to talk to and died.

Please help, this one prove to be real trouble.

**Comment by ajanikow** [comment]
Hello!

For first issue - fixed in 1.0.4, Operator will remove dead coordinators.

About second issue - can you, while creating second deployment, hardcode Agent and DBServer ID's in status? Change of Agent ID is not supported at all in ArangoDB - also change of DBServer ID will enforce data removal (so no expected).

If you want to start clean deployment you need to cleanup path before. otherwise you need to create "prepopulated" status of arango deployment with proper IDs and PVC names, while PVC's should be created before.

Best Regards,
Adam Janikowski.

**Comment by zhuli19901106** [comment]
That's very precise and helpful information, so grateful : )
I'll see about it and try figuring out a solution.

Thanks again.
Good day, signor.
