### ISSUE TITLE
Operator is broken

### ISSUE THREAD

**Issue by DarkBlaez** [arangodb/kube-arangodb#618]
Based on discussion with the metallb folks, the LB is reacting as it should. The operator for ArangoDb is broken and must be causing the deployment and storage Service to be reinfected in to the cluster repeatedly. This becomes evident immediately upon deployment of the operators. I suggest someone take a closer look as this would be happening on a any K3S or K8S cluster. It does not manifest itself in the ArangoDb logs but is certainly present.

To see this in action, spin up a simple k3s or Minikube, inject metallb as the only LB. Deploy the operators, watch metallb logs respond. Metallb functions as it should, this operator is the only operator that exhibits this behavior. Most likely inside one of the containers being deployed.

DB

**Comment by ajanikow** [comment]
Hello!

It should be fixed with latest Operator - annotations update process is fixed.

Best Regards,
Adam.

**Comment by ajanikow** [comment]
Hello!

Version 1.1.1 has been released.

Best Regards,
Adam.
