### ISSUE TITLE
Missing configurable resources somewhere.

### ISSUE THREAD

**Issue by Nainterceptor** [arangodb/kube-arangodb#656]
Hello,

We have created a namespace with hard limits for CPU & memory.

Then, I've deployed the operator into it, thanks to default limits everything is OK for this operator.
Then, We start to deploy a database with configured values for every ResourceRequirements visible in docs (https://www.arangodb.com/docs/stable/deployment-kubernetes-deployment-resource.html)
In events of the deployment, we can see that some creations are failing because quota are not set.
If we create a LimitRange to default quotas, it's working
So, I guess that somewhere, a quota configuration is ignored or not documented

Best regards,
Gaël

**Comment by ajanikow** [comment]
Hello!

Fixed in 1.1.1, will mark PR.

Best Regards,
Adam.

**Comment by ajanikow** [comment]
Hello!

Version 1.1.1 has been released.

Best Regards,
Adam.

**Comment by krzwiatrzyk** [comment]
@ajanikow 

I may be wrong, but I think documentation is missing how to configure resources for that group. Can you tell/point how it should be done in the `ArangoDeployment` manifests to set resources for `id` pod?

FYI @bi3es
