### ISSUE TITLE
Old arch affinity label

### ISSUE THREAD

**Issue by nirroz93** [arangodb/kube-arangodb#662]
Hi, you are using an affinity of beta.kubernetes.io/arch=amd64. It seems to be removed in 1.18 (as it promoted from beta in 1.14).
https://github.com/arangodb/kube-arangodb/blob/8c2d4be3e8b1e64428bc2b397c1cba0455641e4d/pkg/deployment/pod/affinity.go#L62

See https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/20190130-node-os-arch-labels.md

BTW, I'm not using the latest operator but I see this in the code, just checking for myself as I plan to upgrade my cluster from 1.15 to 1.19 - so I just checked the code (didn't check if it really puts the beta affinity in real life).

**Comment by ajanikow** [comment]
Hello!

Thank You! We will fix it in next release.

Best Regards,
Adam.

**Comment by dmosruby** [comment]
@ajanikow Google GKE Autopilot blocks deployments trying to use the node affinity "beta.kubernetes.io/arch" with the following error:

```bash
node affinity is not allowed on labels with keys: <{"beta.kubernetes.io/arch"}>;
Autopilot allows node affinity only on labels with keys: <["topology.kubernetes.io/region", "topology.kubernetes.io/zone", "failure-domain.beta.kubernetes.io/region", "failure-domain.beta.kubernetes.io/zone", "cloud.google.com/gke-os-distribution", "kubernetes.io/os", "kubernetes.io/arch"]>
```

Did the fix for this make it in or is there any way this fix could get prioritized since your comment was from a couple of releases ago?
Tested with `kube-arangodb:1.1.5` on GKE Autopilot `1.18.15-gke.1501`

**Comment by james-innes** [comment]
To fix this just remove `beta` from label `beta.kubernetes.io/arch` like so `kubernetes.io/arch`.
This setting can be found in `arango-deployment.yaml` [here](https://github.com/arangodb/kube-arangodb/blob/91934247797a8bda1672528cc64eaff51e0749e2/manifests/arango-deployment.yaml#L255).
