### ISSUE TITLE
Shutdown / Reboot hangs forever

### ISSUE THREAD

**Issue by inzanez** [arangodb/kube-arangodb#664]
Hi

I have been playing around with ArangoDB in Kubernetes. I noticed that whenever I deploy either ArangoDb directly (docker image, custom deployment), or using the "kube-arangodb" resources, my machine hangs on reboot / shutdown. I am currently testing with a `k3s` single server installation.

Any idea how that shutdown / reboot issues could be fixed? I guess evicting the pod prior to reboot or shutdown could work, but that doesn't feel right somehow.

**Comment by ajanikow** [comment]
Hello!

Which kind of installation are you using? Single one? And do you have only 1 node?

In cases like this operator can be killed before deployment pod will be removed - so it will stuck on finalizer phase. You can play with Pod Priority settings to make sure operator pod will be killed after deployment pods.

Best Regards, 
Adam.

**Comment by inzanez** [comment]
Ok, I will give that a try then. Yes, it is a sungle node installation.
