### ISSUE TITLE
Typo in crd of 1.1.6

### ISSUE THREAD

**Issue by xFragger** [arangodb/kube-arangodb#698]
https://github.com/arangodb/kube-arangodb/blob/78be72645108b2c1779a2daaef4f8b53d464bbd2/manifests/kustomize/crd/arango-crd.yaml#L283

there should be ` name: arangomembers.database.arangodb.com `, otherwise the `kubectl apply -k` will fail

**Comment by ajanikow** [comment]
Hello! Fixed in 1.1.7
