### ISSUE TITLE
Question: How to backup a kubernetes cluster ?

### ISSUE THREAD

**Issue by Flajt** [arangodb/kube-arangodb#708]
Hello everyone,
I'm trying to follow the documentation to backup my Kubernetes Cluster.
I have created my rclone json for a testing with a provider called [Filebase.com](https://filebase.com). My JSON-token looks similar to [this](https://docs.filebase.com/client-configurations/rclone) (if it would be translated to a JSON document). But for whatever reason I don't get an uploaded backup (for testing I've created 4 collections and one document in one). I think I messed up some configuration or it's an issue with the provider (I consider switching to gke), but I'm not exactly sure. 

My db "version": Community
My cloudprovider: Digitalocean
DB Image Version: Default one (Haven't set it in the .yaml file)
Kubernetes Setup:
   - Num. Agents: 3
   - Num. DB Servers: 3
   - Num. Coordinators: 3

`kube-arangodb` version: 1.1.5-1

[My files as a gist](https://gist.github.com/Flajt/936db1232c626d1243fa466f0c7eff57)
Notice: The 2 min timer is just for testing (maybe the issue lies in the small time period?), I also modified the `repositoryUrl`multiple times to: https://s3.filebase.com/buffer, S3://buffer, s3://buffer , s3://buffer/db-backup , filebase://buffer/backup with no avail.

**Comment by ajanikow** [comment]
Hello!

HotBackup is only ArangoDB Enterprise feature (in Operator you can enable this, but Comminity version wont support this operations). For Community you can use Kubernetes CronJob with arangodump command inside (and upload it somewhere).

See https://github.com/arangodb/kube-arangodb/issues/671

Best Regards,
Adam.

**Comment by Flajt** [comment]
@ajanikow Thanks a lot, it seems like I missed the that issue. Sorry for the trouble.
