### ISSUE TITLE
CRD arangomember is deployed by both charts: kube-arangodb and kube-arangodb-crd

### ISSUE THREAD

**Issue by BernhardBerbuir** [arangodb/kube-arangodb#740]
The CRD `arangomember` is deployed by both charts: kube-arangodb and kube-arangodb-crd
=> the last chart wins

I would suggest that only the chart `kube-arangodb-crd` create CRDs.

**Comment by ajanikow** [comment]
Hello!

We want to include CRD creation into `kube-arangodb` chart into crds section. It is recommended by Helm3 right now.

It was first step for migration, we will move other charts under kube-arangodb.

If order of installation is like described in docs - first `kube-arangodb-crd`, then kube-arangodb` - everything should go fine. `kube-arangodb-crd` should install new CRD, after that `kube-arangodb`  should be fine that CRD exists. If this statement is wrong we will update flow, but it passed all manual tests.

Best Regards,
Adam.

**Comment by BernhardBerbuir** [comment]
In my opinion it would be better to separate K8S Cluster admin task and K8S namespace admin tasks as they are different concerns:
* cluster admin: creates CRDs, ClusterRoles and ClusterColebinding
* Namespace admin: creates ServiceAccount and ArangoDB operator

Otherwise only a K8S Cluster admin can use the chart

**Comment by ajanikow** [comment]
Hello!

We can achieve isolation with this approach - CRD from helm are installed as optional. Currently, it is split like this:
- In `kube-arangodb` we support `namespaced` mode, so it can be installed within namespace (without admin access). You can skip CRD installation by helm command flag (--skip-crds).
- CRD can be installed before by system-admin - even using kubectl, helm command - directly from `kube-arangodb` chart.

Best Regards,
Adam.

**Comment by sarahhenkens** [comment]
Thoughts on adding a helm values to wrap the CRD that can be disabled from the `values.yaml`? With some CD systems like ArgoCD, we can't pass in command line arguments to helm

**Comment by ajanikow** [comment]
Hello!

CRD chart is not required anymore.

Best,
Adam.
