### ISSUE TITLE
Struggling with a basic kubernetes instalation

### ISSUE THREAD

**Issue by soickm** [arangodb/kube-arangodb#817]
Greetings,

I am following the instructions at https://www.arangodb.com/docs/3.8/tutorials-kubernetes.html, trying to create a single node installation of arangodb on a locally installed kubernetes cluster.

Is the idea that creating something like this:

kind: "ArangoLocalStorage"
metadata:
  name: "arango-local-storage"
spec:
  storageClass:
    name: arango-storage-class
  localPath:
    - /mnt/arangodb

is enough or must I create the storage class and persistent volume myself? 

I tried both approaches (using the ArrangoLocalStorage and creating the storage artifacts myself) and neither works. In the end, the PVC created by:

apiVersion: "database.arangodb.com/v1"
kind: "ArangoDeployment"
metadata:
  name: "single-server"
spec:
  mode: Single
  auth:
     jwtSecretName: None

always results in this:

Name:          single-server-single-ifymavxo
Namespace:     default
StorageClass:
Status:        Pending
Volume:
Labels:        app=arangodb
               arango_deployment=single-server
               role=single
Annotations:   database.arangodb.com/enforce-anti-affinity: false
Finalizers:    [pvc.database.arangodb.com/member-exists kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Used By:       single-server-sngl-ifymavxo-832023
Events:
  Type    Reason         Age                   From                         Message
  ----    ------         ----                  ----                         -------
  Normal  FailedBinding  2m51s (x62 over 17m)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set

I noticed that I can add the following specs to the ArangoDeployment operator

 dbservers:
    count: 5
    resources:
      requests:
        storage: 80Gi
    storageClassName: SSD

But again it doesn't make a difference. The PVC never gets the "storageClassName" attribute I configure. I tried using dbservers and also single.

Thanks,

Pedro

**Comment by soickm** [comment]
One thing, my local cluster does not have dynamic provisioning ...

**Comment by ajanikow** [comment]
Hello!

Please, reopen the task if you will be able to share the requested information.

Best Regards,
Adam
