### ISSUE TITLE
Problem with deployment Arangodb-Operator on tainted node.

### ISSUE THREAD

**Issue by edk-86** [arangodb/kube-arangodb#826]
Hello all,
I have problem with installtion  arangodb-deploy-operator to k8s on tainted worker node.
ArangoDb-operator is stucked in Pending state:

NAME                                                 READY   STATUS    RESTARTS   AGE
arango-arangodb-operator-operator-758d5db978-wth6z   0/1     Pending   0          13m

Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  15m   default-scheduler  0/14 nodes are available: 1 node(s) had taint {target: arangodb}.

How can i  properly specify nodeSelector for arangodb-operator and also for ArangoDeployment ?

Thank you.

**Comment by ognjen-it** [comment]
Hi @edk-86 ,

you need to specify the type of the Kubernetes cluster (CPU architecture), chart version, etc.
Also, you could post the output of the command: **kubectl get events**.

**Comment by ajanikow** [comment]
Hello!

Please, reopen the ticket if you will find more information.

Tolerations can be added under: https://github.com/arangodb/kube-arangodb/blob/efb5d3fb34273a8208fea271a2459b266b24f762/pkg/apis/deployment/v1/server_group_spec.go#L95

Best Regards,
Adam.
