### ISSUE TITLE
Operator keeps removing externally set pod annotations

### ISSUE THREAD

**Issue by vinzenzs** [arangodb/kube-arangodb#832]
Hello,

In our k8s cluster we are using consul with the connect sidecar proxies. During the init process of sidecars the pod annotation _consul.hashicorp.com/connect-inject-status_ with value injected is set by the consul webhook. 

The pod annotation is immediately removed from the pod. I also tried adding the annotation to the arango deployment with empty string value but the value injected was also overwritten by an empty string.

Also setting the value injected in the arango deployment is not working because consul then thinks the service is already registered. 

Maybe it is possible to disable updates on pod annotations or have to possibility to exempt curtain annotation from updates.

**Comment by ajanikow** [comment]
Hello!

You can solve it in multiple ways:
- define your annotation under https://github.com/arangodb/kube-arangodb/blob/master/pkg/apis/deployment/v1/deployment_spec.go#L114 (wildcard supported)
- change https://github.com/arangodb/kube-arangodb/blob/master/pkg/apis/deployment/v1/deployment_spec.go#L116 to "append" or "disabled"

Best Regards,
Adam.

**Comment by vinzenzs** [comment]
Hello Adam,

thanks for the help. Now it is running.

Best regards,
Vinzenz
