### ISSUE TITLE
[Question] TLS connection

### ISSUE THREAD

**Issue by razbenya** [arangodb/kube-arangodb#899]
Hi, 
In arangodb documentation (when installing without kube operator) we have two keys

1. `--ssl.keyfile filename`  - file should contain server certificate and server private key
2. `--ssl.cafile filename` - file should contain client CA certificate 

But when deploying via arango deployment we have 1 param for `caSecretName` which should contain 2 files 

1. `ca.crt` - PEM encoded public key of the CA certificate
2. `ca.key` - PEM encoded private key of the CA certificate

This is highly confusing, why in arango documentation we need "server private key" and in the deployment documentation you ask for "ca private key" ?  

Also I tried any combination to use my 3 files(listed below) in this secret:

1. ca.crt - ca certificate
2. tls.crt - arango server certificate
3. tls.key - arango server private key

What I see in the deployment is that only `--ssl.keyfile` is being used.

What am I missing? how should I provide a client CA certificate via arango deployment? 

I am referring to: 

- https://www.arangodb.com/docs/stable/programs-arangod-ssl.html
- https://www.arangodb.com/docs/stable/deployment-kubernetes-deployment-resource.html#spectlscasecretname-string

**Comment by ajanikow** [comment]
Hello!

A parameter that you set in ArangoDeployment is just CA - public and private part - which is used later to sign server private keys. (provided via --ssl.keyfile by Operator to process)

The operator does not enforce mTLS - which is enforced by --ssl.cafile. If you want to enforce mTLS then you need to configure it via args in ArangoDeployment. But, remember, this will require your clients to connect with a proper client certificate.

Best,
Adam.

**Comment by razbenya** [comment]
Hey thanks for the quick answer, I still not 100% understand this
So in arango deployment I provide my tls.crt and my tls.key as ca.crt and ca.key ? 

and in the arangodeployment arguments I need to provide my ca.crt ? how can I provide files via arguments? its expecting filename. 

also should I put it for each group (prmr, crdn and agent) ? or there is any global args ?

**Comment by ajanikow** [comment]
In ArangoDeployment you only provide CA, which is used to sign server certificates (so Operator create `tls.key`, then sign it using CA you provided and generate a certificate from this). It is then saved in secret and passed to the process in Pod.

If you want to use default configuration with self-signed CA - you do not have to provide anything.

If you want to provide your CA - you need to specify in `caSecretName` the name of secret with your certificate.

So - in principal:
- `--ssl.keyfile` is managed by Operator, you can only provide your top-level CA via parameter but all server certificates gonna be generated.
- `--ssl.cafile` I do not see any use-case in Operator setup for this, we do not have tests in QA which cover full mutual TLS setup. I would not recommend setting it.

The default setting will have TLS enabled, with self-signed CA and enabled recent and safe ciphers on it. So you do not need to change anything in `spec.tls` section, the Operator will take care of it.

Best, 
Adam.

**Comment by razbenya** [comment]
Hi, thanks again for the answer,
The thing is I don׳t have the CA private key nor I think my organization will provide it, what I have is a generated `tls.crt` and `tls.key` which I want the server to use (and the CA certificate of course). 

Is there any way to provide the operator my own TLS files?

**Comment by ajanikow** [comment]
Hello!

I have verified all possibilities and you cant provide your own certs for Operator Deployment. However, you can start sidecar (for example nginx in TCP mode) which will connect to DB over localhost (enable localPort in arangoDeployment).

There you will be able to provide any cert you want without collision with Operator core functionality.

Best Regards,
Adam

**Comment by ajanikow** [comment]
Hello!

Please, reopen the issue if you need more assistance on this topic.

Best Regards,
Adam.
