### ISSUE TITLE
Config ArangoDB running in Kubernetes 

### ISSUE THREAD

**Issue by flickerfly** [arangodb/kube-arangodb#904]
I've been looking around and I apologize if I've missed it, but I can't seem to find information on a ConfigMap or other means of configuring the ArangoDB instance started by the Operator. For example, I'd like to set `authentication-system-only = false`. 

How do I do that? 

The closest thing I found was the documentation linked below, but it didn't have anything I recognized for the purpose.
https://www.arangodb.com/docs/stable/deployment-kubernetes-deployment-resource.html

**Comment by ajanikow** [comment]
Hello!

You can pass it as a command-line argument: https://www.arangodb.com/docs/stable/programs-arangod-server.html#enabledisable-authentication-for-system-api-requests-only

Best Regards,
Adam.

**Comment by flickerfly** [comment]
@ajanikow Yeah I've seen that, but how do I tell the kube-arangodb operator to do that?

**Comment by ajanikow** [comment]
From docs (link which you have provided): https://www.arangodb.com/docs/stable/deployment-kubernetes-deployment-resource.html#specgroupargs-string

**Comment by ajanikow** [comment]
Hello!

Please, reopen the issue if this did not solve your problem.

Best Regards,
Adam.
