### ISSUE TITLE
Resolve error validating data: ValidationError(Deployment.spec.template.spec.containers[0].resources)

### ISSUE THREAD

**Issue by energia-source** [arangodb/kube-arangodb#947]
Hello,
On GKE i get an error when i try to deploy new version arango-storage-operator.
deployment.spec.template.spec.containers[0].resources: "null" it'a a problem.
Remove this declaration for resolve it.
Thank you

**Comment by ajanikow** [comment]
Hello! We will fix it in next release. Resources values in the helm chart were not propagated correctly (while all other values from same file were fine).

Best Regards,
Adam.

**Comment by wajda** [comment]
Having the same error. @ajanikow is there any workaround we could use meantime?

**Comment by ajanikow** [comment]
Hello!

Fixed in latest release
