### ISSUE TITLE
go.mod file replace error

### ISSUE THREAD

**Issue by windghoul** [arangodb/kube-arangodb#960]
dep folder does not exist and does not know the version and requirements that need to be replaced
<img width="614" alt="image" src="https://user-images.githubusercontent.com/16053291/164430165-e57ee034-52d8-49ef-9357-1d93ba2fe719.png">

**Comment by ajanikow** [comment]
Hello!

Make tools will take care about pulling all dependencies.

**Comment by windghoul** [comment]
ok.Thank's man
